### ISSUE TITLE
Latest and unstable versions of Screencast Keys working on first 3.1 Stable release

### ISSUE THREAD

**Issue by jmiller-simutronics** [nutti/Screencast-Keys#100]
**System Information**
  
* OS: [e.g. Windows]
* Blender version: [e.g. 2.79]
* Add-on version: [e.g. 5.2]

**Expected behavior**  
*The behavior you expect about the feature you reported.*

**Description about the bug**  
*The description about the bug.*

**Screenshots/Files** [Optional]  
*It is good to solve the bug if you attach the screenshots or .blend file.*

**Additional comments** [Optional]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\addon_utils.py", line 387, in enable
    mod.register()
  File "C:\Users\count\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\screencast_keys\__init__.py", line 151, in register
    bpy.utils.register_class(preferences.DisplayEventTextAliasProperties)
ValueError: register_class(...): already registered as a subclass 'DisplayEventTextAliasProperties'

**Comment by jmiller-simutronics** [comment]
That error is from the latest stable version of Screencast Keys. I couldn't get the unstable version to even show up after installation.

**Comment by nutti** [comment]
Many people faced this issue, but this relates to #61 .
Please check it.

**Comment by Viclio** [comment]
I have the exact same issue with Blender 3.1
I tried as well a manual install, both with latest stable and unstable. Unstable doesn't register in the preferences panel.
Same error message with 3.6 as jmiller

**Comment by nutti** [comment]
@Viclio 

Did you try the workaround mentioned #61 

This is a common issue, but there is a workaround.

**Comment by AbdelazizSharaf001** [comment]
Similar issue on linux with another line of code
```
Traceback (most recent call last):
  File "/snap/blender/1925/3.1/scripts/modules/addon_utils.py", line 387, in enable
    mod.register()
  File "/home/<user>/.config/blender/3.1/scripts/addons/screencast_keys/__init__.py", line 154, in register
    utils.bl_class_registry.BlClassRegistry.register()
  File "/home/<user>/.config/blender/3.1/scripts/addons/screencast_keys/utils/bl_class_registry.py", line 63, in register
    bpy.utils.register_class(class_["class"])
ValueError: bpy_struct "SK_Preferences" registration error: 'font_size' IntProperty could not register (see previous error)
```

@nutti reinstailling and reseting didn't work at all - however it worked inside UPBGE
runnig with no environment didn't help for snaped blender - so I think it's not environment
I think it's snap or execution restrictions but don't know how to fix it yet

**Comment by nutti** [comment]
@AbdelazizSharaf001 

This is different issue.
Could you check #73.
Above patch is not included in stable version, but you can try unstable version instead.

**Comment by nutti** [comment]
Today, Screencast Keys v3.7 is released.
I think all issues discussed here will be solved to install new version.

**Comment by Viclio** [comment]
It works ! Thxs ;)
