### ISSUE TITLE
Get Event Aggressively not work

### ISSUE THREAD

**Issue by mac4kent** [nutti/Screencast-Keys#101]
MacOS 12.3
  
MacOS 12.3
Blender 3.1.0 Release and 3.2.0 Alpha is the same.
<img width="729" alt="image" src="https://user-images.githubusercontent.com/4253305/158009033-2108426f-4780-48f9-96a6-9c4a24efa35f.png">
Push the 'G' then 'X' key doesn't appear last "X"
Update of Screencast Key version 3.6.0 (Today is March 11, 2022 at 11:46 AM Pacific Time (California USA)

**Comment by nutti** [comment]
Supported this feature now.
