### ISSUE TITLE
Autosave stops working when screencast keys is on #83 Part 2

### ISSUE THREAD

**Issue by mac4kent** [nutti/Screencast-Keys#102]
Still not work auto save enable but doesn't work.
See youtube: https://youtu.be/7PGfMZMWC1U

I have to open Preferences then click Screencast Key then click save pref before close Blender app.
https://github.com/nutti/Screencast-Keys/issues/83

**Comment by nutti** [comment]
You misunderstood auto save feature.
Auto save feature demonstrates auto save for .blend file not preference.
Please check the post of #83 author.

And I want you to notice that this feature **demonstrate** a auto save feature.
So, #83 error still show up.

I will close this issue for now.

**Comment by mac4kent** [comment]
Ok.
