### ISSUE TITLE
Mouse on PNG feature fail

### ISSUE THREAD

**Issue by mac4kent** [nutti/Screencast-Keys#103]
MacOS 12.3
  
Blender 3.1.0
You have forget to update version number still there same version: 3.6.0 should be 3.7.0 or up on Add-Ons Screencast Key.

(Use Custom Mouse Image)
There mouse on .png few minutes cause black cover that some bug.
![image](https://user-images.githubusercontent.com/4253305/158025255-860daf65-bf55-4511-913e-9f1d13580540.png)
<img width="2566" alt="image" src="https://user-images.githubusercontent.com/4253305/158025358-bf94e6c3-2249-4983-9f7c-bd48e8dcf461.png">
<img width="943" alt="image" src="https://user-images.githubusercontent.com/4253305/158025382-cceb4b4f-8df0-4c9f-b786-e70ea8b4aef8.png">

[MagicMouse Blender screencast key.zip](https://github.com/nutti/Screencast-Keys/files/8237888/MagicMouse.Blender.screencast.key.zip)

**Comment by mac4kent** [comment]
[√] Use Custom Mouse Image
When double click can cause Blender crash guide.
Not matter double and more make crash only 1 (Use Custom Mouse Image)

**Comment by mac4kent** [comment]
When blender open and doesn't appear on .png first place. I have to open Preferences then turn off then on back (Use Custom Mouse Image) appear. Each time open Blender 3.1.0

**Comment by nutti** [comment]
In my environment (macOS 10.14.6, Windows 10 Pro), it works correctly.
I think this is related to environmental issue, but I could not investigate this any more.
If there is some other case studies, I will investigate this issue.

**Comment by mac4kent** [comment]
Ok.
