### ISSUE TITLE
not listing addon in pref

### ISSUE THREAD

**Issue by gakutada** [nutti/Screencast-Keys#104]
* OS: [Windows 11]
* Blender version: [3.1]
* Add-on version: [latest unstable version]

Hi,
when I install it is said its installed but not showing in pref to activate it. Any ideas?
cheers

**Comment by nutti** [comment]
@gakutada 

Did you follow the [installation process](https://github.com/nutti/Screencast-Keys/blob/master/docs/installation.md#manual-install)?
Unstable version needs to be installed manually.

**Comment by gakutada** [comment]
Sweet, worked now, thank you!!
