### ISSUE TITLE
Not working in 3.0.1.

### ISSUE THREAD

**Issue by TheBitcoinBaron** [nutti/Screencast-Keys#105]
**System Information**
  
* OS: [e.g. Windows] Win 10
* Blender version: [e.g. 2.79] v3.0.1
* Add-on version: [e.g. 5.2]  3.5.0

**Expected behavior**  
*The behavior you expect about the feature you reported.*
No errors when ticking box to activate

**Description about the bug**  
*The description about the bug.*
Gives the following error when activated in v3.0.1 for which this version is described as suitable...
https://imgur.com/a/6gtruU2

**Additional comments** [Optional]

**Comment by nutti** [comment]
Same as #61 .
Please see [FAQ](https://github.com/nutti/Screencast-Keys/blob/master/docs/faq.md#failed-to-install-this-add-on)
