### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by TomErnst** [nutti/Screencast-Keys#106]
**System Information**
  
* OS: Windows
* Blender version: 3.1
* Add-on version: 3.7

**Expected behavior**  Should be installable in Blender 3.1

**Description about the bug** 
Installation doesn't work, getting registration error.

**Screenshots/Files** [Optional]  
![Screencast Installation Error](https://user-images.githubusercontent.com/12516281/159195427-48a09eca-d594-42bf-812b-f37a92f34285.png)

**Comment by nutti** [comment]
Same as #61 .
See [FAQ](https://github.com/nutti/Screencast-Keys/blob/master/docs/faq.md#failed-to-install-this-add-on) to try the workaround.
