### ISSUE TITLE
Custom mouse image black after going to another program

### ISSUE THREAD

**Issue by AnityEx** [nutti/Screencast-Keys#108]
**System Information**
  
* OS: Windows 10
* Blender version: 3.1 master
* Add-on version: 3.7.0

**Expected behavior**  
to not reload images inside the addon every time i go out of blender for a sec

**Description about the bug**  
as the title says the custom image stays black after moving to another program, most of the time to pause or  scroll a page in edge but when i get back i see this 
![image](https://user-images.githubusercontent.com/61922421/160261152-8aeb1f41-02d7-4fc3-9c2d-a97649b10639.png)
when previously it looked like this
![image](https://user-images.githubusercontent.com/61922421/160261161-a1ce9ad4-f026-4128-b6f9-c7061e03b376.png)
the workaround i found is to get into the addons settings click inside the location of the images and click out so it reloads them
![image](https://user-images.githubusercontent.com/61922421/160261209-2e2f8d96-fe28-46fa-bc8e-44aeaa62ae89.png)

**Comment by AnityEx** [comment]
checked a little more, apparently it still goes black after a while even if i dont change window, idk if this happens in 3.0

**Comment by nutti** [comment]
Thanks for the report. I fixed this issue.
