### ISSUE TITLE
Click left and Click right cause stay down

### ISSUE THREAD

**Issue by mac4kent** [nutti/Screencast-Keys#109]
When push the 'n' key then click left down and up cause screencast stay down.
Right click then leave cursor from popmenu cause stay right click stay screencast.
3.6.0 it work as well.
BUT
3.7.0 cause mouse stay.
https://youtu.be/uGjvI3F1dU0

**Comment by nutti** [comment]
We could not fix this issue because mouse events will not be triggered while we focus on the specific menu items.
Because of this technical issue, we will not fix this issue for now.

**Comment by mac4kent** [comment]
Allright
