### ISSUE TITLE
Not showing in different tab 

### ISSUE THREAD

**Issue by gakutada** [nutti/Screencast-Keys#110]
Hi, 
Thanks a lot for this lovely addon first of all.

I am not seeing screencast when I moved to different tab such as Shading. I have to make it off and on to show that up.
Any possible way to make it visible in different work space tab?

**Comment by nutti** [comment]
@gakutada 

> different tab such as Shading

Where is this tab located?
This issue seems same as #69

**Comment by mac4kent** [comment]
Yes correct me too. When go other tab and I have to turn uncheck off then check back on appear many times each time to other tab.

**Comment by nutti** [comment]
I confirmed that this is same as #69 .
The workaround can be found [here](https://github.com/nutti/Screencast-Keys/issues/69#issuecomment-911626292).

**Comment by mac4kent** [comment]
Okkkkkk NP
