### ISSUE TITLE
The custom mouse images are frequently missing

### ISSUE THREAD

**Issue by visualworx** [nutti/Screencast-Keys#111]
**System Information**
  
* OS: Windows 11 Pro [21H2 22000.613 the most recent stable version
* Blender version: 3.1.2
* Add-on version: 3.7

**Expected behavior**  
The custom mouse images are showed for good.

**Description about the bug**  
The custom mouse images are frequently missing in a certain period time. If I reload/refresh the images in the addon settings it will be fixed for a while. This is not related to any functions I do in the Blender I guess because this happens no matter what even though I didn't do anything.

**Screenshots/Files** [Optional]  

![image](https://user-images.githubusercontent.com/54339099/163328347-8c22ab25-22ab-4184-b6c8-9c58364bcc57.png)

![image](https://user-images.githubusercontent.com/54339099/163328402-112bb39d-c9a1-498e-b14e-c21ab83108e7.png)

**Additional comments** [Optional]
The new custom mouse image feature is awesome.

**Comment by nutti** [comment]
@visualworx 

It seems that this is a duplication of #108 .
Is this issue also happened even if you use the unstable version?

**Comment by visualworx** [comment]
I never tested it with unstable version. Did you mean unstable version of the addon or the Blender? I don't know if there's unstable version of the screencast key addon. Is there?

**Comment by visualworx** [comment]
![image](https://user-images.githubusercontent.com/54339099/163390472-3e5e4c84-7ec4-4949-9827-49d1f23bfc7c.png)

I just downloaded the newest one by clicking "download zip" like the above. It still happens.

**Comment by nutti** [comment]
@visualworx 

Yes, the unstable version of Screencast Keys add-on.
BTW, did you follow the [manual installation](https://github.com/nutti/Screencast-Keys/blob/master/docs/installation.md#manual-install)?

I could not reproduce this error in the unstable version.
Is there any specific situation when the image was missed.

**Comment by visualworx** [comment]
Great! it works now. I haven't seen the issue since I updated it manually. Apparently, I didn't install it manually. :(

Thanks a lot, I appreciate it. \
