### ISSUE TITLE
Custom Mouse Image Bug

### ISSUE THREAD

**Issue by PMDesign84** [nutti/Screencast-Keys#112]
* OS: Windows 11
* Blender version: 3.1.2
* Add-on version: 3.6

Custom Mouse Image
Use a custom image in place of the displayed mouse icon

Custom image disappears
After a few minutes of use (or not using) the custom image disappears and replaced by a black square.

Disabling and re-enabling screencast keys from the sidebar doesn't fix it. The only way to reactivate the custom image is to go back into preferences and disable the "Custom Mouse Image" box and then re-enable it. Or close Blender and open a new file.

![screencast custom mouse](https://user-images.githubusercontent.com/79392956/163823619-f16b4e46-7e8e-46fe-8eeb-7ee884a120a9.PNG)
![screencast black mouse](https://user-images.githubusercontent.com/79392956/163823623-4b2c978a-04dd-4607-a7b2-b41c83632c46.PNG)

![console](https://user-images.githubusercontent.com/79392956/163823654-f6091daf-0158-4ef2-ab50-aaa5f39a4ca2.PNG)

I'd just like to add that this is a great add-on and the custom mouse image makes it even better. It's just a shame that it doesn't work as expected at the moment. Thank you and great work.

**Comment by nutti** [comment]
Duplication of #108 .
Please use [the unstable version](https://github.com/nutti/Screencast-Keys/blob/master/docs/installation.md#manual-install).
