### ISSUE TITLE
Cant Install plug in Blender 3.1.2

### ISSUE THREAD

**Issue by worm69** [nutti/Screencast-Keys#113]
**System Information**
  
* OS: Windows
* Blender version: 3.1.2
* Add-on version: 3.7

Get a error when try install it like this
![image](https://user-images.githubusercontent.com/12191069/164029461-7baba0c9-434e-40dd-8ece-33bb6f3f854c.png)

**Comment by nutti** [comment]
Duplication of the old issues.
Please see [FAQ](https://github.com/nutti/Screencast-Keys/blob/master/docs/faq.md#failed-to-install-this-add-on) to solve the issue.
