### ISSUE TITLE
Unable to enable addon in Blender 3.1.2

### ISSUE THREAD

**Issue by LengaJenga** [nutti/Screencast-Keys#114]
**System Information**
  
* OS: Windows 10, build 19043.1679
* Blender version: 3.1.2
* Add-on version: 3.7.0

**Expected behavior**  
I expected the addon to enable, it has worked in the past for me.

**Description about the bug**  
I installed Screencast Keys version 3.7.0 from the releases page.
After attempting to enable to addon, I am met with an error.
The addon does not enable after I am shown the error.

**Screenshots/Files** [Optional]  
![image](https://user-images.githubusercontent.com/19176925/164301014-0903958c-18d7-47ce-b84e-79dfa93f0286.png)

**Additional comments** [Optional]
```
Traceback (most recent call last):
  File "E:\Steam\steamapps\common\Blender\3.1\scripts\modules\addon_utils.py", line 387, in enable
    mod.register()
  File "C:\Users\Matthew\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\screencast_keys\__init__.py", line 151, in register
    bpy.utils.register_class(preferences.DisplayEventTextAliasProperties)
ValueError: register_class(...): already registered as a subclass 'DisplayEventTextAliasProperties'
```

**Comment by nutti** [comment]
Duplication of the old issues.
Please see [FAQ](https://github.com/nutti/Screencast-Keys/blob/master/docs/faq.md#failed-to-install-this-add-on) to solve the issue.
