### ISSUE TITLE
The addon just crushed when I use Hardops with Alt +X Mirror tool 

### ISSUE THREAD

**Issue by Jasonjoky** [nutti/Screencast-Keys#115]
**System Information**
  
* OS: [Windows]
* Blender version: [3.1.2]
* Add-on version: [3.7]

https://user-images.githubusercontent.com/93024385/169342750-ee6452bd-db73-45b9-8a6a-64a5230eebc0.mp4

**Comment by Jasonjoky** [comment]
SOLVED: Turn off Get Event Aggressively

**Comment by nurb2kea** [comment]
Doesn't work for me on macos 12.4 & blender 3.3
even after reinstall and restart

**Comment by MPHood** [comment]
Same here.. After pressing Alt+X to mirror with Hardops, the addon stops working
