### ISSUE TITLE
Mouse Icon / HUD isn't updating and stays active with alt navigation!

### ISSUE THREAD

**Issue by nurb2kea** [nutti/Screencast-Keys#116]
**System Information**
  
* OS: macOS 12.4 intel
* Blender version: blender 3.2 / 3.3
* Add-on version: 3.7.0

**Expected behavior**  
Working like the usual screencast keys addon and shows the mouse clicks on the mouse icon/HUD.

**Description about the bug**  
I'm using alt + left/middle/right mouse button with the magic mouse for navigation. It works as expected but the mouse icon/HUD isn't updated well. So after using alt and all three mouse buttons, **all used buttons stay active...**

**Screenshots/Files** [Optional]  

https://user-images.githubusercontent.com/57676085/169673209-feb60b06-9bc8-48e7-9a4b-5e1b0ccc629a.mp4

**Additional comments** [Optional]

**Comment by nutti** [comment]
@nurb2kea 

I don't have magic mouse.
Does this issue also happen when you use other input devices?

**Comment by nurb2kea** [comment]
Yes, I tested it.
I guess it's the problem with the alt key together with the mouse action and a refresh to find out if the button is pressed or not.
This was also present in the former version of screencast keys, but I waited for an update what came the last days.

**Comment by Jasonjoky** [comment]
check this https://github.com/nutti/Screencast-Keys/issues/115#issuecomment-1131908799

**Comment by nurb2kea** [comment]
Doesn't work for me on macos 12.4 & blender 3.3
even after reinstall and restart

you can see it on [Erindale](https://www.youtube.com/c/Erindale) channel too...
https://www.youtube.com/watch?v=r-9cno47nnw

**Comment by mac4kent** [comment]
yes I told them and they disagree with me before. There lot bug new version than before left click and right click cause stay on button within magicmouse. I do use Mac too.

**Comment by nutti** [comment]
@nurb2kea 

I could not reproduce this issue.
Is it same result with default settings of Blender?

**Comment by mac4kent** [comment]
I has been notice many other youtube on screencast key is fail push the left button and middle button and right button lot bug already I can see it. Not matter Windows and Macintosh on Blender 3.1, 3.2, and 3.3 is same I believe. Old previous version it work but new version not work. I am not sure remember 3.5 it work and 3.6 Unknown and 3.7 bug. Lot different youtube I can see already.

**Comment by nutti** [comment]
@nurb2kea 

How about using Screencast Key 3.5?
If @mac4kent 's comment is true, I could investigate this issue more detail.
Unfortunately, I could not fix this issue because of my environment.

**Comment by mac4kent** [comment]
Ok I check. Can you send me link previous version?

**Comment by nutti** [comment]
@nurb2kea @mac4kent 

You can find the link from the [Installation Document](https://github.com/nutti/Screencast-Keys/blob/master/docs/installation.md).

**Comment by mac4kent** [comment]
Thank you for send me link.
Version on screencast key 3.5 only 2.9.xx, 3.0xx (it work)
screencast key 3.6 2.9xx, 3.0xx (it work)
screencast key 3.7 2.9xx, 3.0xx, 3.1xx, 3.2xx, 3.3xx (Special list below)
3.7.0 = 2.9x, 3.0x, 3.1x it work but 3.2x, 3.3x not work as well.

<img width="276" alt="image" src="https://user-images.githubusercontent.com/4253305/173220511-47b19192-4e20-47e0-8f8d-09f214787fcd.png">

**Comment by nutti** [comment]
@mac4kent 

Thanks.
I could find the main reason of this issue.

Some events from mouse can not be fired in Blender since 3.2.
I try to fix this issue, but it seems difficult to solve this issue from add-on level.
So, the solution may be incomplete.

**Comment by mac4kent** [comment]
Good I am glad to help you. I did deeply inspect lot of work and I found out. NP

**Comment by nutti** [comment]
Applied some patches.
Temporary version is now in develop branch.
You can try this version from [this link](https://github.com/nutti/Screencast-Keys/archive/refs/heads/develop.zip).

I think this patch makes better behavior of mouse event.

**Comment by mac4kent** [comment]
This here and my issue ticket is duplicate exactly same.
You give me link (this link.) new version 3.8 it work resolve.
Don't forget on Edit > Preferences on screencast key put version 3.8 not 3.7.
Everything is RESOLVE I inspect on 3.2.0 and 3.3.0 Alpha it worked.

**Comment by mac4kent** [comment]
Screencast Key is so beautiful RESOLVE this youtube awesome. https://youtu.be/xw5DGZdUIfc

**Comment by nurb2kea** [comment]
@nutti  Nooooo, what have you done..... :-) hehe
You done a good job. Thank you very much. 
It's working fine on my end with latest macos & blender 3.3

So now I don't have anything to yell around anymore....
Big THX

**Comment by mac4kent** [comment]
Sure you are welcome. I do use both 3.2.0 and 3.3.0 too both it work.

**Comment by nutti** [comment]
@mac4kent 

We will not release v3.8 only after the small fix.

**Comment by mac4kent** [comment]
Oh I see allright no problem.

**Comment by hitrpr** [comment]
Tested. It work with 3.2. Thanks!

**Comment by mac4kent** [comment]
No problem smile.
