### ISSUE TITLE
Phython: Traceback (most recent call last)

### ISSUE THREAD

**Issue by ABELDESIGN** [nutti/Screencast-Keys#117]
**System Information**
  
* OS: [Windows 11]
* Blender version: [3.1]
* Add-on version: [3.0]

**Expected behavior**
*I want the different keys that I press on the screen to be shown.*

**Description about the error**
*I have an error according to the bug report, in the ops.py file. line 639, inmodal. line 372, in find_redraw_regions. line 305, in calc_draw_rectangle.*

![Captura de pantalla 2022-06-04 013311](https://user-images.githubusercontent.com/105902710/171987713-af7a5d42-b1e5-4a77-ab71-bf65091aaf32.png)

**Comment by nutti** [comment]
Please see [FAQ](https://github.com/nutti/Screencast-Keys/blob/master/docs/faq.md#error-typeerror-an-integer-is-required-got-type-_propertydefered).
The newest version has already fixed this issue.

**Comment by ABELDESIGN** [comment]
Thanks a lot
