### ISSUE TITLE
3.2

### ISSUE THREAD

**Issue by alonelkin** [nutti/Screencast-Keys#118]
I cant use it in 3.2.
here is the error
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\modules\addon_utils.py", line 371, in enable
    mod.register()
  File "C:\Users\Alon Elkin\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\screencast_keys\__init__.py", line 107, in register
    bpy.utils.register_class(preferences.DisplayEventTextAliasProperties)
ValueError: register_class(...): already registered as a subclass 'DisplayEventTextAliasProperties'

basicly i install it but cant check it and get this error
![image](https://user-images.githubusercontent.com/61473174/174906843-b1b3480e-4e2a-445e-866b-88546198e1a8.png)

**Comment by nutti** [comment]
See [FAQ](https://github.com/nutti/Screencast-Keys/blob/master/docs/faq.md#failed-to-install-this-add-on)

**Comment by Almaz** [comment]
I solved this problem: the indicator was not visible before pressing any key.
Now the following problem is observed: in Blender 3.2 the indicator of the middle and sometimes right mouse button is constantly displayed as pressed (in versions 3.0 and 3.1 there is no such thing).
