### ISSUE TITLE
Installing through UI doesn't work in 2.80

### ISSUE THREAD

**Issue by Caleb9** [nutti/Screencast-Keys#12]
**System Information**
  
* OS: Windows 10
* Blender version: 2.80
* Add-on version: master (8070928e15d42384cc764f7cd4fb6e4882582721)

**Expected behavior**  
Plugin installs from zip file using User Preferences in Blender.

**Description about the bug**  
Plugin doesn't show up in Add-ons menu after installing from .zip file. I had to manually copy contents of `src/screencastkeys` into `%USERPROFILE%\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\screencastkeys\`

**Comment by Hawkpath** [comment]
Are there any error messages in the system console when you try to install?

**Comment by Caleb9** [comment]
Hi @Hawkpath, nope:

![image](https://user-images.githubusercontent.com/7767011/69181338-303de880-0b0f-11ea-8657-f03618d8ccb6.png)

However after I manually removed it from file-system, I guess it was still enabled in the preferences. Then installing it showed "Missing script files" next to where you can enable it in Add-ons. Maybe that's a hint? After I disabled it, it just disappeared.

**Comment by raindropsfromsky** [comment]
I have Blender 2.82 running on Windows 10 Home (64 bits), and I face the same issue.
But in my case the installation has created the folder here:

![image](https://user-images.githubusercontent.com/9047168/71556832-20e18180-2a63-11ea-9ffd-130289b700ae.png)

This could be a wrong path issue.

**Comment by ArtemkaJS** [comment]
It still doesn't work for me, after all this manipulations.

**Comment by ArtemkaJS** [comment]
Ok, i solved this issue. Run Blender as administrator and install addon as zip file.

**Comment by nutti** [comment]
I think this issue comes from the installation method.
We need to download .zip file from [here](https://github.com/nutti/Screencast-Keys/releases/tag/v3.0) instead of [this](https://github.com/nutti/Screencast-Keys/archive/master.zip).
In my environment, it works correctly.

If you have any further issues, please reopen this issue or create new issue.
