### ISSUE TITLE
Mouse icon Bug

### ISSUE THREAD

**Issue by Wolfgang-IX** [nutti/Screencast-Keys#120]
**System Information**
  
* OS: Windows 10 64 bit
* Blender version: 3.2.0
* Add-on version: 3.7.0

**Expected behavior**  
Mouse icon show which button is pressed correctly

**Description about the bug**  
Mouse icon showed that middle & right click is still pressed even though it isn't, sometime left click too

**Screenshots/Files** [Optional]  
![image](https://user-images.githubusercontent.com/47208316/175763626-3baf33df-37ac-4aba-b6af-2b7666246156.png)

**Additional comments** [Optional]

**Comment by nutti** [comment]
Same as #116
