### ISSUE TITLE
All three mouse buttons stay active after clicking.

### ISSUE THREAD

**Issue by 3dcinetv** [nutti/Screencast-Keys#121]
**System Information**
  
* OS: Windows 10, x64 pro
* Blender version: 3.2.1
* Add-on version: 3.7.0

**Expected behavior**  
MMB click should dissapear. But after clicking for the first time it stays clicked (active)

**Description about the bug**  
Whenever capturing keys using Blender 3.2.1, the middle mouse button press represented with the mouse graphic, stays active.
It also happens with the LMB. The only button normally working (and showing correctly) is the left mouse button clicks.
Sometimes ALL 3 BUTTONS in the mouse graphic stay ON. 

**Screenshots/Files** [Optional]  
[https://imgur.com/a/s0AHyhY](url)

**Additional comments**
All other keys work fine, it's the mouse representation that's failing. 
The addon is very useful to represent screen mouse clicks.

**Comment by nurb2kea** [comment]
This was explicit fixed with version 3.7,... for mac, what I can say.
Just tested it with the todays blender v3.2.1 on latest macos and it works fine, even with blender v3.3.
I'm not sure if there is a difference , but I would switch off the addon, uninstall it, restart blender and install again.

**Comment by 3dcinetv** [comment]
I confirm, it is working now. I deleted, old prefs/addon. Reinstalled. It works correctly. Thank you.

**Comment by LucasAlfare** [comment]
Got same bug here. Also tried:

> ...switch off the addon, uninstall it, restart blender and install again.

Didn't work for me.

Same system info here:

- OS: Windows 10, x64 pro
- Blender version: 3.2.1
- Add-on version: 3.7.0
