### ISSUE TITLE
Stops to work over spreadsheet area

### ISSUE THREAD

**Issue by hitrpr** [nutti/Screencast-Keys#122]
**System Information**
  
* OS: win 10
* Blender version: 3.1+
* Add-on version: 3.7.0 last available code

**Expected behavior**  
work independent on type of area

**Description about the bug**  
If I expand spreadsheet area below screencast overlay, it terminate work.
Error:

```
Python: Traceback (most recent call last):
  File "C:\Users\Ad\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\screencast_keys\ops.py",
line 1725, in modal
    space_type = self.SPACE_TYPES[area.type]
KeyError: 'SPREADSHEET'

location: <unknown location>:-1
```

[video demo:  ](https://youtu.be/QyJsxNEtpjI)

**Comment by nutti** [comment]
This issue is now fixed.
Thanks @hitrpr !
