### ISSUE TITLE
Mouse Release Button

### ISSUE THREAD

**Issue by Calantee** [nutti/Screencast-Keys#123]
**System Information**
  
* OS: [Windows 11]
* Blender version: [3.2]
* Add-on version: [3,7 latest from blender market]

After using the mouse button, they remain active. They can be fixed by holding them a little longer (doesn't work with MMB) but I don't thins that's how it should work. I have reinstalled addon, reset blender and PC and problem still exist.

![image](https://user-images.githubusercontent.com/110686075/183144165-03aa6ad8-89b2-44f0-8117-c0dc0e012fbb.png)

**Comment by nutti** [comment]
Duplication of #116 

Please use unstable version for now.
I will release 3.8 in near future.
