### ISSUE TITLE
mouse buttons stay permanently lit up after releasing.

### ISSUE THREAD

**Issue by 3d-illusions** [nutti/Screencast-Keys#125]
**System Information**
  
* OS: win 10
* Blender version: 3.3 alpha
* Add-on version: 3.7

mouse buttons stay permanently lit up after releasing.
![image](https://user-images.githubusercontent.com/22356973/183266685-f8e1756c-722b-4b3b-90e2-f5af64b542fb.png)

**Comment by nutti** [comment]
Same as #116.
Use the unstable version for now.
