### ISSUE TITLE
Get Event Aggressively is bug August 9, 2022

### ISSUE THREAD

**Issue by mac4kent** [nutti/Screencast-Keys#126]
<img width="392" alt="image" src="https://user-images.githubusercontent.com/4253305/183815732-89f3edee-2106-4abe-9d84-d5b38fb2b9e3.png">

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/4253305/183815680-7bbef27e-ca75-48c0-9f02-b4d2dd88f5da.png">

Blender 3.2.2

[√] Get Event Aggressively
doesn't work correct.
I must turn off then turn on then it work.
There doesn't save on preferences on Screencast Key within Get Event Aggressively.

**Comment by nutti** [comment]
Fixed this issue.

**Comment by mac4kent** [comment]
It work for sure and perfect and still 3.7.0 smile.
