### ISSUE TITLE
Mouse Hold status issue for 3.2.2

### ISSUE THREAD

**Issue by gakutada** [nutti/Screencast-Keys#127]
**System Information**
  
* OS: [e.g. Windows]
* Blender version: 3.2.2
* Add-on version: 3.7

Hi at 3.2.2 Blender I am not seeing Mouse Hold status working. It is always on hold. 
Any idea whats the issue?
thanks

**Comment by nutti** [comment]
Same as #116 .
For now, please use the unstable version.
