### ISSUE TITLE
Blender 3.2.2 does not display keystrokes

### ISSUE THREAD

**Issue by Jean-MichelSmith** [nutti/Screencast-Keys#128]
**System Information**
  
* OS: Mac OS X (M1)
* Blender version: 3.2.2
* Add-on version: 3.7

**Expected behavior**  
Keystrokes should be displayed in vendor

**Description about the bug**  
The addon installs and appears to be configurable, but when active, no actual keystrokes our mouse presses are displayed.

**Screenshots/Files** [Optional]  
Default blend file, with a few meshes added while testing the addon.  Did NOT use the aggressive mode that might crash blender (if this is a hard requirement please document).

Thank you!

**Comment by nutti** [comment]
Is it same after you push `Tab` key in 3D Viewport?
I think changing the mode between object mode and edit mode solves this kind of issue.
And if possible, please upload your detailed option.

> Did NOT use the aggressive mode that might crash blender (if this is a hard requirement please document).

This information has already documented [here](https://github.com/nutti/Screencast-Keys/blob/master/docs/tutorial.md#get-event-aggressively).

**Comment by Jean-MichelSmith** [comment]
Thank you.  

I got it working and suspect you can put this down to user error/unfamiliarity, but you may want to check my screenshots to confirm.  Configuring/Activating in preferences is not sufficient, however, once the the box at the top works of the N-sidebar fine.  I assume this isn't a mismatch between the two locations where the configuration is defined, and that it is intended to be activated manually via the n-sidebar (which makes sense).

There was no need to toggle between EDIT and OBJECT mode, it works fine without doing that.

When you asked for "detailed option" is the info in the screen shot what you intended?

<img width="662" alt="Screen Shot 2022-09-01 at 9 47 49 PM" src="https://user-images.githubusercontent.com/112571789/188049411-d47d87c2-43ce-49e4-b00e-b937b7939bc0.png">
<img width="1427" alt="Screen Shot 2022-09-01 at 9 48 23 PM" src="https://user-images.githubusercontent.com/112571789/188049496-09a5d7c4-2c19-42ec-bd32-8b9b3ab4fb69.png">
<img width="1419" alt="Screen Shot 2022-09-01 at 9 48 59 PM" src="https://user-images.githubusercontent.com/112571789/188049522-6a662517-5130-427b-946a-114aedd5a68b.png">

**Comment by nutti** [comment]
I was glad to solve your issue.
If there is another issue, we will welcome to open new issue.

**Comment by Jean-MichelSmith** [comment]
Thank you.  You've written an awesome add-on.

all the best,

Jean
--
Jean-Michel Smith
55 East Erie Street #1701
Chicago, IL 60611
t: (312) 373-1763
c: (917) 652-1166
