### ISSUE TITLE
Autosave blender file not working 

### ISSUE THREAD

**Issue by gakutada** [nutti/Screencast-Keys#129]
### System Information
  
* OS: [e.g. Windows]
* Blender version: 3.2.2
* Add-on version: debug version

### Expected behavior
Hi 
I see auto save is not doing when I use screencast debug version, is it known issue?
thanks

**Comment by nutti** [comment]
@gakutada 

Does this [FAQ](https://github.com/nutti/Screencast-Keys/blob/master/docs/faq.md#auto-saving-blend-file-feature-is-disabled-when-screencast-keys-add-on-is-enabled) help you?
If you want to enable auto saving while Screencast Keys is on, you need to turn on `Auto Save` option.

**Comment by gakutada** [comment]
Yes thanks!

**Comment by nutti** [comment]
No prob.
I will close this issue now.
