### ISSUE TITLE
The Addon does not detect ESC key, or the LMB click after S (scaling).

### ISSUE THREAD

**Issue by raindropsfromsky** [nutti/Screencast-Keys#13]
Windows 10 Home (64 bit)
Blender 2.82
Screencast keys: Devp version (just installed it)

Sometimes the ESC key is part of a sequence of commands.
For example, select a face of cube, and press E, ESC and S, and then scale the face.

In this sequence, the addon does not display the press of the ESC key.

Similarly, if we press S and then drag and press LMB to complete the scaling, the addon does not display the LMB click.

But after that, it detects all LMB clicks.

**Comment by nutti** [comment]
@raindropsfromsky 

Thanks for your report, and sorry for late reply.
This issue is same as #6 .

In model mode, we can not catch the event correctly.
This is a limitation which comes from the implementation of Blender Internal.

**Comment by 0Curtain0** [comment]
@nutti What's the probability that this limitation will be addressed in Blender 2.9? 
Is this limitation a low priority for the Blender devs? 
Maybe I'm looking at the wrong Blender manifest.

**Comment by 3diuk** [comment]
Have you made the blender devs aware of this limitation?

**Comment by nutti** [comment]
@0Curtain0 @3diuk 

Yes. It's a well-known issue.
BTW, I came over this problem in particular situation in a dirty way .
After some testing, I will release this feature as experimental feature.
Please wait for next release.

**Comment by nutti** [comment]
This issue is now resolved.
Please see #6 .
