### ISSUE TITLE
Mouse buttons are displayed as "jammed"

### ISSUE THREAD

**Issue by sspetersmith** [nutti/Screencast-Keys#130]
### System Information
  
* OS: [e.g. Windows]
* Blender version: [ 3.3]
* Add-on version: [3.7.0]

Once I press and release the middle or right buttons on my mouse, the Screencast add-on displays them as if I keep pressing those buttons. I've tried all possible solutions already: reinstalling Blenders, reinstalling Screencast, installing older versions of Screencast, and changing all possible settings in the add-on itself (including getting Event Aggressively). How can this issue be resolved?

### Screenshots/Files
Please see the attached screenshot

![image](https://user-images.githubusercontent.com/74813625/189276463-f19c3789-a24e-49be-9687-93026813bc77.png)

**Comment by sspetersmith** [comment]
I'm running Blender on Windows

**Comment by nutti** [comment]
Same as #116.
Use the unstable version for now.

**Comment by sspetersmith** [comment]
Your solution has worked well, thank you very much. To whoever is facing the same issue: follow this installation manual for unstable version :
https://github.com/nutti/Screencast-Keys/blob/master/docs/installation.md#manual-install

It is important to know that the standard installation process won't work for the unstable version.

**Comment by nutti** [comment]
Glad to hear that.
We will release v3.8 in near future (maybe next week end), so this issue will be solved in the standard installation process.

**Comment by nurb2kea** [comment]
> ...We will release v3.8 in near future (maybe next week end), so this issue will be solved in the standard installation process...<
I just noticed with blender 3.1 to 3.4 that ScreencastKeys consumes in my case on macOS up to 100 MB of memory.
Have a try and watch the memory in blender statusbar while enabling/disabling the addon in preferences.
(It's still not enabled in the 3d-viewport, in the preferences but!)
