### ISSUE TITLE
Click not work display text and mouse. September 11, 2022

### ISSUE THREAD

**Issue by mac4kent** [nutti/Screencast-Keys#131]
<img width="698" alt="image" src="https://user-images.githubusercontent.com/4253305/189876923-843b538c-6f7c-4f8e-aaab-056513221d66.png">

Blender 3.3.0

Screencast Key 3.8.0 recent download.
<img width="3200" alt="image" src="https://user-images.githubusercontent.com/4253305/189877335-208c0a98-6797-4914-ae44-4514c916d8fd.png">

See Youtube https://youtu.be/dPCaewYhxgY

Show Mouse Events:
     Mode: there some bug.

**Comment by nutti** [comment]
Fixed this issue.
