### ISSUE TITLE
Cannot install add-on

### ISSUE THREAD

**Issue by luckychris** [nutti/Screencast-Keys#132]
### System Information
  
* OS: [e.g. Windows] 

<img width="509" alt="image" src="https://user-images.githubusercontent.com/232549/193058369-ce9f21e7-3a77-4a31-a028-71669125cfdc.png">

* Blender version: [e.g. 2.79]

<img width="99" alt="image" src="https://user-images.githubusercontent.com/232549/193058420-0ee4163a-f439-4161-8d96-b232d5558686.png">

* Add-on version: [e.g. 5.2]

<img width="196" alt="image" src="https://user-images.githubusercontent.com/232549/193058531-2f668b7a-514a-4c5f-a98d-a4aabd54cd42.png">

### Expected behavior

*The behavior you expect about the feature you reported.*

### Description about the bug**

*The description about the bug.*

Error appears when i try to enable the add-on.

<img width="661" alt="image" src="https://user-images.githubusercontent.com/232549/193058229-3cb108d9-0cf2-4f05-844e-78f6ea989a7c.png">

### Screenshots/Files [Optional]  

*It is good to solve the bug if you attach the screenshots or .blend file.*

**Comment by draconistheory** [comment]
![bugreport](https://user-images.githubusercontent.com/114700009/193140344-ee1489e3-370b-4a1f-8011-0d0dde4755ef.png)
I am getting a similar error when trying to enable the add-on.

**Comment by nutti** [comment]
Some of the issues are same as old issue. See [FAQ](https://github.com/nutti/Screencast-Keys/blob/master/docs/faq.md).
I recommend you to use the latest version.
Especially, v3.0 is too old to run in the latest Blender.

**Comment by nutti** [comment]
@luckychris 

I could not reproduce your error (Blender 3.4 alpha, Screencast Keys v3.8).
Is it still popup when you reinstall Blender or add-on?

**Comment by luckychris** [comment]
if i use 3.8 and blender 3.4 alpha - > screencast keys doesn't even appear in the add-on list

**Comment by nutti** [comment]
@luckychris 

Did you follow the [installation process](https://github.com/nutti/Screencast-Keys/blob/master/docs/installation.md)?
I think this is an environmental issue.

**Comment by luckychris** [comment]
yes, i tried the automatic installation -> as i wrote, after choosing the zip file the add-on does not appear in the add-on list

**Comment by luckychris** [comment]
and even checking "get event aggressively" doesn't solve this problem, as you can see in my gif.

**Comment by luckychris** [comment]
it's veeeeeery weird, after restarting blender...now it works....i have no idea why....

**Comment by nutti** [comment]
@luckychris 

**Get Event Aggressively** needs to be enabled before enabling Screencast Keys.
I think this is the cause of the issue.

**Comment by mac4kent** [comment]
> it's veeeeeery weird, after restarting blender...now it works....i have no idea why....

There is not weird. You have to restart your Blender always when add-ons. Same Avastar add-ons. Each time restart and install add-one always.

Many other kind add-ons you must restart Blender before install.

**Comment by luckychris** [comment]
@mac4kent : 
your quote:"You have to restart your Blender always when add-ons"

sorry, but this is nonsense. I have installed a lot of add-ons and just a very few like Flipfluids - need a restart of Blender, but they are giving a visible warning to the user that they should restart Blender. Would be helpful if screencast keys would give that hint too.

**Comment by mac4kent** [comment]
> @mac4kent : your quote:"You have to restart your Blender always when add-ons"
> 
> sorry, but this is nonsense. I have installed a lot of add-ons and just a very few like Flipfluids - need a restart of Blender, but they are giving a visible warning to the user that they should restart Blender. Would be helpful if screencast keys would give that hint too.

Visible Warning I see that one before many times.
I make youtube about Blender with Screencast Key.

**Comment by mac4kent** [comment]
> @mac4kent : your quote:"You have to restart your Blender always when add-ons"
> 
> sorry, but this is nonsense. I have installed a lot of add-ons and just a very few like Flipfluids - need a restart of Blender, but they are giving a visible warning to the user that they should restart Blender. Would be helpful if screencast keys would give that hint too.

Viewer Warning I see that one before many times.
I can send my youtube link. https://youtu.be/g-yP4lBH6Sg
