### ISSUE TITLE
the axis key (x,y,z) when moving an object with G X won't be shown

### ISSUE THREAD

**Issue by luckychris** [nutti/Screencast-Keys#133]
### System Information
  
* OS: [e.g. Windows]
* 
<img width="318" alt="image" src="https://user-images.githubusercontent.com/232549/193060422-7a5d7b62-98ad-41fb-a304-9d9438531af7.png">

* Blender version: [e.g. 2.79]
<img width="193" alt="image" src="https://user-images.githubusercontent.com/232549/193060383-d48b6247-e1b9-45bd-ba25-4d533852b4f3.png">

* Add-on version: [e.g. 5.2]
<img width="561" alt="image" src="https://user-images.githubusercontent.com/232549/193060341-80e2aed3-98bb-4662-94f0-39a0768d144f.png">

### Expected behavior

*The behavior you expect about the feature you reported.*

### Description about the bug**

*The description about the bug.*

### Screenshots/Files [Optional]  

*It is good to solve the bug if you attach the screenshots or .blend file.*

### Additional comments [Optional]

https://user-images.githubusercontent.com/232549/193061560-cae84f56-1adb-433b-aa52-ce7f465844fe.mov

**Comment by nutti** [comment]
Please use [v3.8](https://github.com/nutti/Screencast-Keys/releases/tag/v3.8).
v3.6 does not support **Get Event Aggressively** option.
ref: https://github.com/nutti/Screencast-Keys/blob/master/docs/faq.md#failed-to-get-event-while-the-modal-operation-is-running-eg-g--x-s--y-
