### ISSUE TITLE
Error when trying to enable the addon.

### ISSUE THREAD

**Issue by HypnoWorld** [nutti/Screencast-Keys#138]
### System Information
  
* OS: [e.g. Windows]
* Blender version: [e.g. 3.3.1]
* Add-on version: [e.g. 3.8.0]

For some odd reason, I keep getting an error anytime I try to enable the addon. I opened the console, and this is what it shows me.

![Screenshot 2022-11-29 232759](https://user-images.githubusercontent.com/119479303/204723641-297b0499-2c29-420a-95f8-b79e43831b39.png)]  

I tried older versions, but they don't seem to work either. Please help.

**Comment by nutti** [comment]
@HypnoWorld 

Is it possible to uninstall and install this add-on?
This error seems curious to me.

From the code based check, there is no issue.

https://github.com/nutti/Screencast-Keys/blob/67892c0dd1ef260303887685218cf099c94de2ff/src/screencast_keys/__init__.py#L93-L100

**Comment by HypnoWorld** [comment]
Yeah that was the issue. I think I had previous versions of it before. Thanks for the reply!

**Comment by nutti** [comment]
@HypnoWorld 

Does this still happen in the latest version?

**Comment by HypnoWorld** [comment]
Not anymore. My blender version is 3.3.
