### ISSUE TITLE
right button, and middle wheel stuck in blender 3.3

### ISSUE THREAD

**Issue by keneso9** [nutti/Screencast-Keys#139]
### System Information
  
* OS: Windows 8.1
* Blender version: 3.3.0
* Add-on version: [e.g. 3.7.0]

### Expected behavior

To briefly show which button is pressed

### Description about the bug**

When clicking the rmb, and middle wheel the two remain highlighted

### Screenshots/Files [Optional]  

![screencast-01](https://user-images.githubusercontent.com/14238370/205327135-514e4b25-67a5-4697-a057-9f4e6faf3493.jpg)

**Comment by nutti** [comment]
This issue has already fixed by #116.
Please use v3.8 instead.
