### ISSUE TITLE
Blender 3.4.0 is ready

### ISSUE THREAD

**Issue by mac4kent** [nutti/Screencast-Keys#140]
Blender 3.4.0 is ready https://www.blender.org/download/releases/3-4/
Experimental: Get Event Aggressively turn enable.
Both Win, Mac too.

**Comment by nutti** [comment]
@mac4kent 

Are there any issues about Get Event Aggressively option for 3.4.0?
As you may know, Get Event Aggressively option is available for all versions from Screencast Keys v3.7.
You don't need to wait the new release anymore if there is no issue.

**Comment by mac4kent** [comment]
ScreenCast Key version 3.8
Push the G then X key appear "G" then doesn't appear "X".
See youtube: https://youtu.be/2u2vDAuZLUY
Blender 3.3.x -VS- Blender 3.4.0 there have lot and lot largest change code because of Geometry Nodes plus lot change cause not work on Get Event Aggressively.

**Comment by nutti** [comment]
> Blender 3.3.x -VS- Blender 3.4.0 there have lot and lot largest change code because of Geometry Nodes plus lot change

This does not relate to whether **Get Event Aggressively** option works or not.

I saw your YouTube video.
I think you need to turn on **Get Event Aggressively** option before enabling the Screencast Keys.
Actually, the option itself works on my environment.

**Comment by mac4kent** [comment]
Strange Open Preferences then Add-ons then search Screencast Key.
Click check box turn on "Get Event Aggressively" then (Save Preferences) button then quit and open I can see G then X appear it work that weird because Push the N Key to enable doesn't work must have Preferences enable.

**Comment by nutti** [comment]
This seems not an issue, and is expected behavior.
Close it for now.
