### ISSUE TITLE
Screencast broke my entire blender program

### ISSUE THREAD

**Issue by swapmasterx** [nutti/Screencast-Keys#142]
* OS: [Windows 10]
* Blender version: [3.4]
* Add-on version: [3.8]

Installed plugin, no key visualization so I restarted Blender

Blender will no longer fully open, staying stuck on a grey screen.

No project file is applicable as the program will no longer open.
Plugin also does not show in my blender files despite being the only thing added before program restart.

**Comment by nutti** [comment]
@swapmasterx 

Please show us the configuration of the add-on.
Is this related to #137 ?
#137 happens when you enable **Enable On Startup** option.

**Comment by nutti** [comment]
@swapmasterx 

Any update about this issue?

**Comment by nutti** [comment]
Close this issue for now because of no reaction.
