### ISSUE TITLE
Mouse wheel zoom in and out unusable

### ISSUE THREAD

**Issue by newemka** [nutti/Screencast-Keys#145]
Windows 10 
Blender 3.4.1
Add-on version: 3.8

Once the screencast addon is activated it makes the use of mouse wheel up and down to zoom in and out in Nodes editor windows impossible. 
Same issue in shader editor and geometry nodes.

**Comment by newemka** [comment]
My apologies I just noticed that this issue is already investigated

**Comment by nutti** [comment]
As you noticed, this issue has already discussed at #143
