### ISSUE TITLE
Blender 3.5.0 crash guide during Screencast Key January 12, 2023

### ISSUE THREAD

**Issue by mac4kent** [nutti/Screencast-Keys#146]
13.2 Beta (22D5038i)
Blender 3.5.0 crash guide during Screencast Key is enable
Edit > Preferences on System tab
See details below.
See this Report a Bug link.
https://developer.blender.org/T103817

**Comment by nutti** [comment]
We will not support the alpha version which is still unstable.

Please wait until the beta or stable version is released.

**Comment by mac4kent** [comment]
Ok.

**Comment by mac4kent** [comment]
Please check there is bug fixed on Blender 3.5.0 Alpha I am show you picture 
Only for Mac on METAL on System tab Preferences.
<img width="3200" alt="image" src="https://user-images.githubusercontent.com/4253305/214923699-d8084529-bcda-457f-878d-528c5a097c87.png">
