### ISSUE TITLE
Zooming on all other windows except 3D Viewport causes blender to stop responding

### ISSUE THREAD

**Issue by SantrixYT** [nutti/Screencast-Keys#148]

**Comment by jmdenis** [comment]
+1 I have the same issue

**Comment by B1Trash** [comment]
@nutti 
Which release version is this working on? I've tried 3.4.0, 3.4.1 and the 3.5 alpha. Both 3.4 versions lag on mouse wheel on timeline/dope sheet and node editor windows. The release notes for 3.4.1 do not have your bugfix listed (T103210)

The 3.5.0 alpha version works smoothly on the timeline & dope sheet, but the node editor is still extremely laggy.

**Comment by nutti** [comment]
Reported this issue to D.B.O.
https://developer.blender.org/T104274

This issue seems to relate to https://developer.blender.org/T103210.

**Comment by nutti** [comment]
@B1Trash 

I think the previous issue has already fixed.
I checked 3.5.0 alpha version works smoothly on the timeline & dope sheet as you mentioned.

The issue on the node editor is a similar but a bit difference of the previous one.
So, we need to wait that Blender has fixed this issue.

**Comment by B1Trash** [comment]
Thank you so much for looking into it. I thought these would have been the same fix. I guess that's why I'm not a developer.

**Comment by nutti** [comment]
From the discussion on D.B.O, I found this issue can be solved from the add-on side.
I fixed this issue now.

**Comment by gpofcher** [comment]
I came to report this bug, but it's already fixed! Thanks for your work on this addon, it's super helpful for me and my students.

**Comment by B1Trash** [comment]
Thanks Nutti... I tested it out and it's smooth as butter again!  Cheers!
