### ISSUE TITLE
Mouse image of .png not work within METAL Blender 3.5.0 February 9, 2023

### ISSUE THREAD

**Issue by mac4kent** [nutti/Screencast-Keys#149]
<img width="392" alt="image" src="https://user-images.githubusercontent.com/4253305/217923561-def89e01-f39c-4d82-9e50-da0871c01eef.png">

[   ] Use Custom Mouse Image within System > GPU Backend METAL it worked show picture.
( Stroke line mouse)

[√] Use Custom Mouse Image within System > GPU Backend METAL will not work doesn't show picture.
<img width="2916" alt="image" src="https://user-images.githubusercontent.com/4253305/217923501-5b6cc5e8-b3b7-47b1-9257-85690067e50c.png">

See Youtube: https://youtu.be/b0ors-Cd-L0

**Comment by nutti** [comment]
@mac4kent 

Please do not make an issue for alpha version.
As I said in the past, we will not support alpha version for the current rule.

**Comment by nutti** [comment]
This issue is now fixed by migration to gpu module from bgl module.
ccae721

**Comment by mac4kent** [comment]
[√] Screencast Key turn enable appear error.
<img width="2984" alt="image" src="https://user-images.githubusercontent.com/4253305/220138952-d999ffc5-4224-45ba-8202-d301563f1dd6.png">

**Comment by nutti** [comment]
What is the detail error?

I don't have any metal environment.
So, please post the result of the shader compilation.
This can be seen by the system console.

**Comment by mac4kent** [comment]
Your iMac already have kind METAL.
I will take a time screen record when I have free time.

**Comment by mac4kent** [comment]
There ya go YouTube https://youtu.be/vQpz_WXKPnA
