### ISSUE TITLE
Add a option to customize the tab

### ISSUE THREAD

**Issue by xan2622** [nutti/Screencast-Keys#15]
Hi.

---
**Description about the feature**  

Could you please add **an option** in the preferences of your add-on **to give the user the choice of the tab** to display your add-on? (in order to move the add-on from its own tab to a custom one).

Some users might want to place your add-on in the *Edit* or in the *Tool* tab... (or elsewhere).

I invite you to read this related topic (if you want): https://blender.community/c/rightclickselect/dzdbbc/ 

According to the number of votes, there are many people who don't like having many tabs vertically in the N panel. The only workaround is to add an option in the addon preferences.

This option is very convenient for the user, especially when there are many add-ons that add their own tab on the N panel (it could become overcrowded vertically). 

---
**Are you willing to contribute about this feature. (Yes/No)**  

No.

---
**Screenshots** 

![6cb58ec90d0eaf2859819909e32075473fcd9f47](https://user-images.githubusercontent.com/1732773/79038461-b7cce680-7bd9-11ea-8eb7-97311b8566ba.jpeg)

![1173cda700ee4af649f858070ca426f970587afb](https://user-images.githubusercontent.com/1732773/79038462-bc919a80-7bd9-11ea-9d6f-d518dd2f198e.jpeg)

---

**Additional comments** [Optional]

Maybe you could have a look at the source code of these (free) add-ons (to reuse the lines related to this feature)?

**Backface Hiding** :  https://gitlab.com/ChameleonScales/Backface_Hiding

**SpeedRetopo** : https://gumroad.com/l/speedretopo

Thank you in advance for considering to add this option.

**Comment by nutti** [comment]
@xan2622 

Thanks! It seems good idea to provide an option to hide panel.
After some investigations, I will add this feature.

**Comment by nutti** [comment]
Added this feature.
This feature will be available in next release.
