### ISSUE TITLE
"Caps Lock" key error makes Screencast stop showing keystrokes

### ISSUE THREAD

**Issue by blackcorvo** [nutti/Screencast-Keys#16]
**System Information**
  
* OS: Windows 10 Home (1909)
* Blender version: 2.8
* Add-on version: 3.0

The add-on shows an error message and straight up stops registering keystrokes if you press Caps Lock. In order to keep using it, you have to go to the options tab (N) to desselect and select the add-on in order for it to restart and work again.

Screenshot of error:
![image](https://user-images.githubusercontent.com/29687112/79698842-fa3d9580-8261-11ea-9984-0d7460f087b3.png)

I have not noticed the same error wirh other locking keys (Num Lock, Fn Lock, etc), and I encountered the error by accidentally pressing the Caps Lock key, but I thought it was relevant to put it here so the issue can be resolved and doesn't cause frustration to other users. Thank you.

**Comment by nutti** [comment]
@blackcorvo 

This issue is duplicated with #7.
This issue was already fixed by #10.
Could you try master branch or wait next release.
