### ISSUE TITLE
autosave with unstable version

### ISSUE THREAD

**Issue by gakutada** [nutti/Screencast-Keys#162]
Hi 
Possibly known issue but seems auto save is not working when I use unstable version of screencast key?
cheers

**Comment by nutti** [comment]
@gakutada 

It seems that the auto save option works correctly.
Could you share your detail configuration and system information?

**Comment by gakutada** [comment]
Actually it does not do auto save in 3.9.0 screencast in Blender 3.4.1 in windows.
Could you check this please?

**Comment by nutti** [comment]
When Screencast Keys is enabled, you can not use the auto save feature builtin the Blender.
Instead, this add-on supports the custom feature for the auto saving.

You can see how to enable this feature from below document.
https://github.com/nutti/Screencast-Keys/blob/master/docs/tutorial.md#auto-save

I confirmed this works correctly in my environment.

**Comment by gakutada** [comment]
Thanks!
I tried that but still not saving in my env..

**Comment by nutti** [comment]
> I tried that but still not saving in my env..

Please show me the evidence why the auto saving feature does not work.

Again, the default auto save feature still can not be used even if you enable above feature.
Check the directory where the blend file is stored by the default auto save.
The directory should be `C:\Users\<username>\AppData\Local\Temp\` on Windows.

**Comment by gakutada** [comment]
Oh it did now, strange it was not showing before but now good!
Thank you so much!!

**Comment by nutti** [comment]
Great news.
If you have an additional issue in future, let me know again.
