### ISSUE TITLE
Images mouse and line mouse size bug.

### ISSUE THREAD

**Issue by mac4kent** [nutti/Screencast-Keys#164]
<img width="392" alt="image" src="https://user-images.githubusercontent.com/4253305/229143189-7934a171-963b-485a-8da5-b8c0856bd553.png">

Blender 3.5.0 March 29, 2023
Screencast Key 3.9.0
Line Thickness 1.49 then change to 1.50 cause disappear.
Image mouse disappear.

See Youtube:
https://youtu.be/cjIPMJtNd4M

**Comment by nutti** [comment]
Fixed now.

**Comment by mac4kent** [comment]
Mouse thickness is pass resolve.
Image mouse is bug doesn't appear.
(Use Custom Mouse Image)
(Use Image Size)
<img width="3200" alt="image" src="https://user-images.githubusercontent.com/4253305/230620476-20648b01-bcd7-44b6-830a-4821509ce71a.png">
[Screencast Key picture.zip](https://github.com/nutti/Screencast-Keys/files/11179361/Screencast.Key.picture.zip)
