### ISSUE TITLE
addon enabled breaks node editor mousewheel zooming in blender versions below 3.6

### ISSUE THREAD

**Issue by 3d-illusions** [nutti/Screencast-Keys#165]
full details of bug here: https://projects.blender.org/blender/blender/issues/106640#issuecomment-916507

basically with screencast keys enabled, mousewheel node editor zooming freezes blender.

**Comment by nutti** [comment]
This issue has already fixed Screencast Keys v3.9.

**Comment by 3d-illusions** [comment]
ah ok, sorry.
