### ISSUE TITLE
Image .png doesn't appear.

### ISSUE THREAD

**Issue by mac4kent** [nutti/Screencast-Keys#166]
Blender 3.5.0 and up.
3.5.1 too
Blender 3.5.0 March 29, 2023
Screencast Key 3.9.0
Mouse thickness is pass resolve.
Image mouse is bug doesn't appear.
(Use Custom Mouse Image)
(Use Image Size)

![image](https://user-images.githubusercontent.com/4253305/230795070-444c7141-698d-4cbd-ae33-b5abc59a369d.png)

**Comment by nutti** [comment]
@mac4kent 

I did the same test on my macOS (with Metal) environment, and worked.
Check the display location.

**Comment by mac4kent** [comment]
Oh allright I had hard time to see I have low vision and finally uncheck and check again (Use Image Size) until finally back correct size from very tiny picture.
https://youtu.be/HK9I1-MpfkQ
You may close a ticket.
---------------
I want let you know I did click check, uncheck, check, uncheck (Use Custom Mouse Image) fast many times cause Blender crash guide.

**Comment by mac4kent** [comment]
I am tell you know. Good news Blender 3.6.0 Alpha did fix much better than 3.5.0 and 3.5.1
Push the N key there has been fixed only for Blender 3.6.0 Alpha.
I did report a ticket long time ago. They reach my report a ticket. They still work some more very details.
https://youtu.be/R1WhT8sQE94

**Comment by nutti** [comment]
Good news. Then, I will close this issue for now.

**Comment by mac4kent** [comment]
Sure of course.
