### ISSUE TITLE
Crash when opening a new file from compositing workspace

### ISSUE THREAD

**Issue by Febulix** [nutti/Screencast-Keys#167]
### System Information
  
* OS: macOS Monterey (12.6.3)
* Blender version: 3.5.0
* Add-on version: 3.9.0

### Description about the bug

Blender always crashes when I open a new, empty "_General_" scene under the following circumstances:
You have to have the attached scene open where only compositing is being done in the "_compositing_" workspace. Nothing else is necessary. Screencast Keys must be enabled, even if it is not used in this particular case.

### Steps to reproduce the bug

1. Open the attached .blend file
2. Go to "_File_" → "_New_" → "_General_"

### Actual behavior

Blender crashes with the following traceback:
```
Traceback (most recent call last):
  File "/Users/felix/Library/Application Support/Blender/3.5/scripts/addons/screencast_keys/ops.py", line 2069, in intialization_callback
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
```
There is no information in the `blender.crash.txt` file.

### Expected behavior

No crash ;)

### Files
[Report.zip](https://github.com/nutti/Screencast-Keys/files/11190868/Report.zip)

**Comment by nutti** [comment]
Thanks for the report.
This issue is now fixed.
