### ISSUE TITLE
Show last operator Label + ID Name cause line without word

### ISSUE THREAD

**Issue by mac4kent** [nutti/Screencast-Keys#168]
MacOS 13.4
Blender 3.5.0 and up.
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/4253305/231044904-75563fc2-e613-4083-b975-d7ae18ba2a69.png">

See youtube about Show last operator -> Label + ID Name cause line without word.
https://youtu.be/DnRR9VcdrXM

**Comment by nutti** [comment]
@mac4kent 

In your video, the ID name seems to be hidden by the footer.
You should change the display location (i.e. move to upper place).

**Comment by mac4kent** [comment]
Oh really? strange and I get you.
I just drag X and Y move up and I can see appear text.
I think about purple line drag move down and X and Y become 0 and I can see there.
<img width="1460" alt="image" src="https://user-images.githubusercontent.com/4253305/231166363-d6fc2630-f88b-4bd6-abf3-b301caacddfc.png">

How can I set force float front and I am not sure know yet. 
You may close a ticket or whatever you can text and mouse force to be front I guess.

**Comment by nutti** [comment]
Then, I will close this issue for now.
Actually, floating the display to the front is not possible from add-on side because of the Blender limitation.

**Comment by mac4kent** [comment]
Oh really allright.
