### ISSUE TITLE
Bug on Blender 3.5

### ISSUE THREAD

**Issue by LampageStudio** [nutti/Screencast-Keys#169]
Hello, I'm only reporting an issue that happened here.
For the newest Blender's version (3.5), when I move the Shader Editor with the addon version 3.7 activated, the software is crashing because of the addon. I also tried the 3.10 version, but it doesn't works, the software returns me the module is installed, but nothing happens. Could you help me?

**Comment by nutti** [comment]
>  I also tried the 3.10 version, but it doesn't works,

Is the Blender also crash even if the factory settings?

> the software returns me the module is installed, but nothing happens.

What does this mean?
Please tell me this more concretely.

**Comment by nutti** [comment]
@LampageStudio 

Is there any update about this issue?

I could not reproduce your issue.
It helps me a lot to share your information more detail.

**Comment by nutti** [comment]
Close this issue for now because of no response for a long time.
Please reopen or make an issue if there are still issues.
