### ISSUE TITLE
Feature Request: Option to align Screencast-Keys to the Left or Right

### ISSUE THREAD

**Issue by 0Curtain0** [nutti/Screencast-Keys#17]
**Description about the feature**  
 It would be nice if the Screencast-Keys add-on had an option to align the displayed keys to the right side of the 3D View as well.
 - There are times where a popup panel may appear on the left side of Blender's 3D view which can make visibility of the keys or panel difficult. 
 - The solution would be to change the offset of the screencast-keys to the right side, but that solution could be a little inconvenient for people who **resize their Blender window** or **move the Blender window to a different monitor with different screen resolution**.  

Thank you for developing this add-on.

-------------------------

**Are you willing to contribute about this feature. (Yes/No)**  
Yes, but I can't contribute code since I am still learning how to. 
However, I can test releases and provide feedback.

-------------------------

**Screenshots** [Optional]  
*It is good to understand the features if you attach the screenshotsfile.*

-------------------------

**Additional comments** [Optional]

**Comment by nutti** [comment]
@0Curtain0 

Thanks for the feature request.
I think this will be achieved by changing `offset` property or `origin`.
Does this feature still need to fulfill your requirement?

**Comment by 0Curtain0** [comment]
@nutti 
Unfortunately, changing the offset may still require constant adjustment when moving the Blender window to a different monitor with different screen resolution or when resizing the Blender window.  

Try maximizing your Blender window, then change offset so that the screencast keys appear on the right side of 3D View. 
If you now resize the Blender window, the screencast keys will start to disappear from the 3D View.

I tried Set Origin, and it's a nice feature. I tried setting it to the N panel, but the screencast keys are hidden when the N panel is hidden, but still cool feature.

I was hoping the screencast keys can have an extra option to align relative to the right side of the 3D view. Then use offset for minor adjustments. 
Right now, offset works relative to the left side of 3D View.

I believe Jayanam's Shortcut VUr already has this ability. https://github.com/jayanam/shortcut_VUr

**Comment by nutti** [comment]
@0Curtain0 

Thanks for your explanation.
I understood why this feature is useful.
I think addding an option 'align' to the Panel is one of solutions.

**Comment by nutti** [comment]
@0Curtain0 

I added this feature.
Before release this feature, could you try it?
This feature can be usable in this [pre-release](https://github.com/nutti/Screencast-Keys/archive/spike_17.zip) version.

The option 'align' is located in preference panel.

<img width="488" alt="github_20200502" src="https://user-images.githubusercontent.com/1463952/80859676-8194fb00-8c9d-11ea-80f6-184cb885cd8a.png">

After your check, I will re-struct UI, and some additional option.
Thanks for your great feedback!

**Comment by 0Curtain0** [comment]
@nutti 
I forgot to ask, is there a description of the different **Origin** points? 
- **Region**, **Area**, **Window** 

Here is a test demo for **Right** alignment: https://gfycat.com/graciousradiantfritillarybutterfly 

Also, the text itself may need to be aligned to right as well. 
![Text Align Right](https://www.cssnewbie.com/wp-content/uploads/2016/10/Screen-Shot-2016-10-30-at-2.51.09-PM.png) 
![Text Align Right](https://d1nhio0ox7pgb.cloudfront.net/_img/i_collection_png/512x512/plain/text_align_right.png)

You get the idea. 

Keep up the good work.

**Comment by nutti** [comment]
@0Curtain0 

Nice explanation!
[New version](https://github.com/nutti/Screencast-Keys/archive/spike_17.zip) aligns text as well.
Could you try this again?
If there is no issue, I will release this feature ASAP.

> I forgot to ask, is there a description of the different Origin points?

This is a origin point itself which is indicated by the option name.
If you are not familiar with them, you may check [the document](https://docs.blender.org/manual/en/latest/interface/index.html#window-system).

Thanks for your cooperate.

**Comment by nutti** [comment]
This feature is now merged to master branch.
