### ISSUE TITLE
Blender 3.5, 3.6 -VS- 4.0

### ISSUE THREAD

**Issue by mac4kent** [nutti/Screencast-Keys#171]
### System Information
  
MacOS 13.5
Blender 3.5 (fine)
Blender 3.6 (fine)
Blender 4.0 (bug)

### Expected behavior
Blender 4.0 Alpha
check box turn on enable then push the Command, Option, Control, or Shift appear bug.
I want to let you know very early and you will possible to get know to fix bug take your time.

<img width="2108" alt="image" src="https://github.com/nutti/Screencast-Keys/assets/4253305/bebb8269-7385-46df-86ef-24d49942140b">

**Comment by nutti** [comment]
`blf.size` is now deprecated the 3rd parameter, so I fixed this in advance.

**Comment by mac4kent** [comment]
Good job resolve.
