### ISSUE TITLE
os crash

### ISSUE THREAD

**Issue by allen20010405** [nutti/Screencast-Keys#172]
### System Information
  
* OS: windows 10 
* Blender version: 3.6
* Add-on version: 5.2

### Expected behavior

screen cast the keys i am pressing

### Description about the bug**

crash windows the instent it is turned on

### Screenshots/Files [Optional]  

it instently crasses, so i can't get any

### Additional comments [Optional]

shows library not found error before windows crashes with no error code
[30377-artwork-mixamo_rig.zip](https://github.com/nutti/Screencast-Keys/files/11742164/30377-artwork-mixamo_rig.zip)
by the way, i also always have this on, might this be the problem?

**Comment by nutti** [comment]
@allen20010405 

Could you clear your problem more?
Please consider to provide the exact step to reproduce or .blend file.

I could not reproduce your error.

**Comment by nutti** [comment]
Close this issue due to the no reaction.
Please reopen this issue or comment if you still have the issue.
