### ISSUE TITLE
Some keys are not displayed

### ISSUE THREAD

**Issue by sspetersmith** [nutti/Screencast-Keys#174]
* OS: Windows
* Blender version: 3.6.1 LTS
* Add-on version: 3.10

I'm a fan of your add-on. For several months already the add-on is not displaying all keyboard clicks. For example, when I select the cube and press G (screencast will display that G was pressed) and then press Z, screencast won't display the fact that Z was pressed. Please refer to the attached video. 
This  type of issue happens with other combinations as well (e.g. pressing G and then pressing SHIFT+X etc.)
How can I solve this issue?

https://github.com/nutti/Screencast-Keys/assets/74813625/78cfe82f-5457-43d7-b0b2-010a2be3d37c

**Comment by nutti** [comment]
See [FAQ](https://github.com/nutti/Screencast-Keys/blob/master/docs/faq.md#failed-to-get-event-while-the-modal-operation-is-running-eg-g--x-s--y-).

Maybe your **Get Event Aggressively** option is disabled.

**Comment by sspetersmith** [comment]
Thank you this helped! Even though I believe I've tried it earlier and it didn't work. Now it is working :)

**Comment by nutti** [comment]
I was glad to hear that.
Close this issue foe now.
