### ISSUE TITLE
Mouse/Font Display Errors - Blender 3.3 LTS

### ISSUE THREAD

**Issue by Kaitou-3D** [nutti/Screencast-Keys#177]
### System Information
  
* OS: Windows 10
* Blender version: 3.3.9 LTS
* Add-on version: 3.10-3.11

## Issue
When running either 3.10 or 3.11 with 3.3.9 LTS, various errors will occur

### with 3.10:
https://github.com/nutti/Screencast-Keys/assets/26198203/112ecb0c-3b1a-4c9f-a693-e105c5c50f53
- History will not display correctly
- Mouse image will not display
- Enabling mouse display will hide hotkey display
- Operator display does work

### with 3.11
https://github.com/nutti/Screencast-Keys/assets/26198203/e1444689-6d21-4e22-b7c7-53679fcc97a1

- Unusable

I was able to roll back to addon versions 3.8 and 3.9 with no issues

**Comment by nutti** [comment]
This is a side-effect of https://github.com/nutti/Screencast-Keys/commit/00a42de67b3c2b6b40259999a3c2bac82b9e7724 .
We need to fix this to consider the case of version dependency.

**Comment by nutti** [comment]
This issue is now fixed
