### ISSUE TITLE
object align to transform orientation crashes blender immediately

### ISSUE THREAD

**Issue by 3diuk** [nutti/Screencast-Keys#18]
**System Information**
2.9

bpy.ops.transform.transform(mode='ALIGN') causes immediate crash since you uploaded the new version 4 hours ago with the aggressive option enabled.

**Comment by nutti** [comment]
@3diuk 

> 2.9

Is this a blender version?
I think v3.1 can only support Blender 2.82 currently, that I say to use it carefully at https://github.com/nutti/Screencast-Keys/issues/6#issuecomment-618901969.
Sorry for lack of description.

**Comment by 3diuk** [comment]
yep, it's a blender version, I haven't tried in 2.8, but presumably the bug will still occur.  Hang on I'll try it now.

**Comment by 3diuk** [comment]
yep, it also crashes the official 2.80 release, although in 2.80 it didnt crash for a few seconds (until I made google chrome the active window), whereas in 2.90 it crashes as soon as you click the operator in the object menu.

**Comment by 3diuk** [comment]
with aggressive option disabled, no crashes in either version of blender.

**Comment by nutti** [comment]
@3diuk 

Thanks for your investigation!
Current implementation depends on Blender 2.82, so it will be crushed when this feature is used in other Blender version.
I think [c_structures.py](https://github.com/nutti/Screencast-Keys/blob/master/src/screencast_keys/utils/c_structures.py) should be switched among Blender versions.
Please wait until we implement this.

**Comment by nutti** [comment]
@3diuk 

I will support this feature in below blender versions.

* 2.79
* 2.80
* 2.81
* 2.82

BTW, how do you use Blender 2.9?

**Comment by 3diuk** [comment]
https://builder.blender.org/download/

These are the daily buids.  It's what most people use, very few people use the official release, even studios use the daily builds because they have all the bug fixes and newest features.  Rock solid too.

**Comment by nutti** [comment]
@3diuk 

Great!
I will check it. Thanks!

**Comment by nutti** [comment]
@3diuk 

I tested [this version](https://github.com/nutti/Screencast-Keys/archive/spike_18.zip) and works correctly in Blender 2.9.
BTW, I could not reproduce your error in Blender 2.80.
Is there any condition to reproduce this error?
Thanks for your help!

**Comment by 3diuk** [comment]
The crash happened as soon as I clicked off of blender to another open application, but the last operation before the crash was the one mentioned above.

**Comment by nutti** [comment]
I could not reproduce this issue when the last operator is `bpy.ops.transform.transform(mode='ALIGN')`.
But Blender will be crashed when I change the space type (eg. VIEW_3D -> Python Console) in my environment.
Fortunately, I came over this issue, but I'm not sure it is a same cause you faced with.

**Comment by nutti** [comment]
Fixed this issue now (It's in master branch).
But we should use aggressive mode with carefully.

**Comment by 3diuk** [comment]
awesome thanks.
