### ISSUE TITLE
lost file and crash blender

### ISSUE THREAD

**Issue by allen20010405** [nutti/Screencast-Keys#181]
### System Information
  
* OS: windows
* Blender version: 3.5.x
* Add-on version: newest

### Expected behavior

screencast the keys i press

### Actual behavior

*reports lost file and crashes blender soon after*

### Screenshots]  

*none*

### Additional comments [Optional]

it could be because i have 360 safegard on , but when i turned it off the problen remained, no idea, i'm no coder.

**Comment by nutti** [comment]
@allen20010405 

Could you give me the exact step to reproduce this error?
The step is too generic to investigate your error.

**Comment by allen20010405** [comment]
i will open blender 3.5, and turn on screen cast keys, then when i use the mouse buttons it just crash

**Comment by allen20010405** [comment]
same for blender 3.6

**Comment by nutti** [comment]
Please show me the error message or log after crashing the Blender.
In my environment, I could not reproduce your error.

**Comment by nutti** [comment]
Close this issue due to no response.
