### ISSUE TITLE
hotkey highlight

### ISSUE THREAD

**Issue by allen20010405** [nutti/Screencast-Keys#182]
### Description about the feature

*highlight hotkeys in color*

### Are you willing to contribute about this feature. (No)

*i'm no coder*

### Screenshots [Optional]  

*um, maby not.*

**Comment by nutti** [comment]
@allen20010405 

Is it possible to show me the mockup design about this enhancement to concrete your idea?

**Comment by allen20010405** [comment]
L _# select all linked mesh #_

**Comment by allen20010405** [comment]
something like t6his

**Comment by nutti** [comment]
> L # select all linked mesh #

This design expands the width of display field which interferes the default Blender UI.
Also, your request does not match the title "hotkey highlight".
What is the "hotkey" in this context?

**Comment by nutti** [comment]
Close this issue due to no response.
