### ISSUE TITLE
freezes blender for around 1 minute when disabling from the n panel

### ISSUE THREAD

**Issue by 3d-illusions** [nutti/Screencast-Keys#184]
### System Information
  
*windows 10 pro
* Blender version: 4.1
* Add-on version: 3.11

disable addon from n panel to see issue.

**Comment by nutti** [comment]
I could not reproduce this error on the commit `01a2bd03695f`.
Could you try the newest Blender or tell me the concrete commit?

**Comment by nutti** [comment]
@3d-illusions 

Any update?

**Comment by nutti** [comment]
Close this issue due to the no response.
