### ISSUE TITLE
Error message when I want to activate the addon - Blender 4.0 / Screencast Keys 3.12

### ISSUE THREAD

**Issue by magmatin** [nutti/Screencast-Keys#188]
### System Information
  
* OS: windows
* Blender version: 4.0
* Add-on version: 3.12

**### Expected behavior**

solution when importing the addon

**### Description about the bug**

When I install the addon, I get this error message when I want to activate the addon :
(I have read the forum and the error persists on my side.)
```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 401, in enable
    mod.register()
  File "C:\Users\magal\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\screencast_keys\__init__.py", line 157, in register
    register_updater(bl_info)
  File "C:\Users\magal\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\screencast_keys\__init__.py", line 103, in register_updater
    updater.init(config)
TypeError: AddonUpdaterManager.init() missing 1 required positional argument: 'config'
```

### Screenshots/Files [Optional]  

![A7qMEAP](https://github.com/nutti/Screencast-Keys/assets/145924777/8edde093-0d6c-41c8-9b5d-095f5095dc17)
![3KnwrJs](https://github.com/nutti/Screencast-Keys/assets/145924777/e1fdc86b-527d-46db-8e6c-fb4ef8b91ed8)

Thank you,

Magali Grande

**Comment by nutti** [comment]
@magmatin 

Check this issue https://github.com/nutti/Screencast-Keys/issues/186 .

**Comment by magmatin** [comment]
@nutti thanks 😅

**Comment by nutti** [comment]
@magmatin 

Is your issue solved?

**Comment by magmatin** [comment]
Oui merci :)

**Comment by nutti** [comment]
OK, then close this issue.
