### ISSUE TITLE
Feature Request: Options to re-size Shadow/Outline thickness

### ISSUE THREAD

**Issue by 0Curtain0** [nutti/Screencast-Keys#19]
**Description about the feature**  
- Add a **Shadow Size** or **Shadow Thickness** option.
-- This should be helpful when the text color matches the viewport color and when recorded video bitrate doesn't display the text shadow/outline properly.
- Another alternative option you can add, if possible, is a backcolor/highlight box option for all key strokes.

**Are you willing to contribute about this feature. (Yes/No)**  
I can provide feedback.

**Screenshots** [Optional]  
*It is good to understand the features if you attach the screenshotsfile.*

**Additional comments** [Optional]

**Comment by nutti** [comment]
@0Curtain0 

Thanks for the requests.
Adding this feature looks good to me.

**Comment by nutti** [comment]
@0Curtain0 

I found that shadow size is not changeable in current Blender API.
But, I think adding shadow seems good to me.
What do you think below looks?
If it is good for you, I will apply this change.

![github_20200501](https://user-images.githubusercontent.com/1463952/80785612-d2342780-8bbb-11ea-9ed0-e615a3475a79.png)

**Comment by 0Curtain0** [comment]
@nutti Both very good, and the backcolor/highlight is very nice and visible. 
The backcolor/highlight version will have changeable alpha channel too? 

-------

Also, what do you think of giving **x7** a separate color option? 
Or separate color option for **Select ('view3d.select')** ?

**Comment by nutti** [comment]
@0Curtain0 

> The backcolor/highlight version will have changeable alpha channel too?

Sorry, this option is not good for my add-on due to the add-on's specification.
When the text overlap between "Window" region and "Toolbar" region, we could not handle these situation if we have alpha channel.
Instead, I will provide disable option to hide the background.

> Also, what do you think of giving x7 a separate color option?
> Or separate color option for Select ('view3d.select') ?

It seems good option.
But, I'm afraid that too many option confuses the user.
What do you think about it?

**Comment by 0Curtain0** [comment]
@nutti 

> Sorry, this option is not good for my add-on due to the add-on's specification.
> When the text overlap between "Window" region and "Toolbar" region, we could not handle these situation if we have alpha channel.
> Instead, I will provide disable option to hide the background.

That's fine, and no worries.

> It seems good option.
> But, I'm afraid that too many option confuses the user.
> What do you think about it?  

It's not urgent. Maybe it can be made a separate issue and then come back to it in a few months or whenever the next Blender python API update happens.  That should be enough time to make things more intuitive.

When I get time, I will see if I can contribute any ideas to improve the UI of the Screencast-Keys side panel. 

I'm currently learning python, but my eyes aren't experienced enough to look through Blender python code just yet.

**Comment by nutti** [comment]
@0Curtain0 

> When I get time, I will see if I can contribute any ideas to improve the UI of the Screencast-Keys side panel.

Great news! Thanks.
I committed current version which enables to add shadow/background of text.

I think your contribution should be different issues, so closes this issue for now.
This project is contribution welcomed.
We are waiting your contribution in future!
