### ISSUE TITLE
Screencast not displaying 4.0.2

### ISSUE THREAD

**Issue by Jordain** [nutti/Screencast-Keys#191]
### System Information
  
* OS: Windows 11
* Blender version: 4.0.2
* Add-on version: 3.12.0

It seems like other people having it working for their blender 4.0.2, but for me the screen cast is not showing up on my screen. No error, enabled in addons and in the sidebar.

Please advise. Thanks!

![Screenshot 2024-01-11 205914](https://github.com/nutti/Screencast-Keys/assets/46907245/dd3d3c0f-e5a5-44f6-9952-c38fcd8ba989)

**Comment by nutti** [comment]
@Jordain 

Did you restart the Blender after installing the add-on?
If this issue is not fixed, could you reinstall the add-on?

At least, the add-on works for my environment.

**Comment by Jordain** [comment]
The blender restart worked this morning. Thanks. I had restarted blender a couple times yesterday, and it wasn't showing up, might have been because I had opened it to quickly after and the process didn't fully quit.
