### ISSUE TITLE
The overlay is not visible when I switch to another tab

### ISSUE THREAD

**Issue by kkol4anov** [nutti/Screencast-Keys#192]
### System Information
  
* OS: Windows
* Blender version: 4.0.2
* Add-on version: 3.12.0

### Expected behavior

When switch from Layout tab to another (Modeling, Sculpting, Shading, etc) where is 3D Viewport editor, the overlay should be visible.

### Description about the bug

The overlay become not visible when I switch to another tab until I disable the checkbox on the addon tab and enable it again.

### Screenshots/Files

https://github.com/nutti/Screencast-Keys/assets/39926218/7ada2897-173e-4256-aa62-0ad5b588849a

**Comment by nutti** [comment]
@kkol4anov 

This seems to be the same as https://github.com/nutti/Screencast-Keys/issues/69#issuecomment-911626292.
Please check it.

**Comment by kkol4anov** [comment]
Yes, changing the Origin option to Window was helped. It is not too comfortable, the layout keeps position when area is resized, but it works. Thank you!
