### ISSUE TITLE
Screencast Keys addon settings accumulate over on userpref.blend upon saving settings

### ISSUE THREAD

**Issue by johnyc90** [nutti/Screencast-Keys#195]
### System Information
  
* OS: Reproductible on Windows and Linux, probably Mac as well
* Blender version: 3.6
* Add-on version: 3.9.0 - 3.13.0

### Expected behavior

The userpref.blend size should stay constant if no settings are updated. Screencast Keys make the userpref size grows every time the user preferences are saved.

### Description about the bug**

Screencast Keys make the userpref size grows every time the user preferences are saved after blender a blender restart. About 100kb every time the preferences are saved. Disabling the addon drastically reduces the userpref size. 

For people who thinker a lot with their configs, this can lead to the userpref.blend file bloating to incredibly large proportions (as shown in the screenshots below with my userpref.blend being as big as 35mb!) and can become problematic for people who use blender sync or other services to sync configurations, as well as greatly slowing down blender startup.

This behavior was witnessed on two windows machines running Windows 10 and Windows 11, and a Linux machine running Fedora.

### Screenshots/Files [Optional]  
With Screencast Keys enabled
![image](https://github.com/nutti/Screencast-Keys/assets/2996374/7b39f8f4-dd48-4aef-a42a-ae23d08967b7)
![image](https://github.com/nutti/Screencast-Keys/assets/2996374/230f8059-640f-48a6-85d1-99f42470294c)
![image](https://github.com/nutti/Screencast-Keys/assets/2996374/e7d8c0d5-8078-4c06-b7c3-22fea7981f9c)
With Screencast Keys disabled
![image](https://github.com/nutti/Screencast-Keys/assets/2996374/9bf19071-b374-4473-884c-585d9ea70afd)
![image](https://github.com/nutti/Screencast-Keys/assets/2996374/104453f0-95bb-4d13-8f38-6e42c49deb86)
After re-enabling the addon
![image](https://github.com/nutti/Screencast-Keys/assets/2996374/4353ec0b-c12b-446f-a26f-c0100bc81ec9)

*It is good to solve the bug if you attach the screenshots or .blend file.*

**Comment by jplc-miclos** [comment]
thank you @nutti! You're the best!

**Comment by johnyc90** [comment]
thank you @nutti! You're the best!
