### ISSUE TITLE
can not show the mouse and operation

### ISSUE THREAD

**Issue by zhang-chongxiang** [nutti/Screencast-Keys#196]
I download the latest version of screencast key, but it shown nothing in my blender. Don't know why.

![Uploading image.png…]()

**Comment by zhang-chongxiang** [comment]
![Uploading 屏幕截图 2024-03-07 013415.png…]()

**Comment by zhang-chongxiang** [comment]
Even if I start this plugin, it still cannot display the mouse and my actions.

**Comment by nutti** [comment]
@zhang-chongxiang 

Could you share the detail information like a screenshot?
I think your screenshots are broken.

**Comment by nutti** [comment]
@zhang-chongxiang 

Is there any update?

**Comment by Frederica97** [comment]
I ran into the same issue. Thanks, Nutti, for taking a look. 
![Screenshot 2024-03-26 at 9 56 24 PM](https://github.com/nutti/Screencast-Keys/assets/31479492/4c4f553b-5a91-443c-968c-30e80f966e98)

**Comment by zhang-chongxiang** [comment]
> I ran into the same issue. Thanks, Nutti, for taking a look. ![Screenshot 2024-03-26 at 9 56 24 PM](https://private-user-images.githubusercontent.com/31479492/317095142-4c4f553b-5a91-443c-968c-30e80f966e98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MDUwMTYsIm5iZiI6MTcxMTUwNDcxNiwicGF0aCI6Ii8zMTQ3OTQ5Mi8zMTcwOTUxNDItNGM0ZjU1M2ItNWE5MS00NDNjLTk2OGMtMzBlODBmOTY2ZTk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDAxNTgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyY2U3MTJkODM3N2RmMzc5MmZlMDhjY2NhNDc1ZTQxY2ZkZjU4OWYwN2FmNDcxNTFlMTU2Y2MzZGZlNjhmNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5Dkyls-TvSF7brBvsDk9jGCKxF-O_qXXcYYkuE7Z5ZA)

yes，like this

**Comment by whompyjaw** [comment]
Ya I am running into this issue as well? I have it enabled and nothing is showing up...
<img width="1345" alt="Screenshot 2024-03-26 at 21 39 35" src="https://github.com/nutti/Screencast-Keys/assets/25990657/8ddef0bb-34e7-40cf-a1eb-50f8c79d6bdf">

**Comment by whompyjaw** [comment]
This was using 3.13. 

Downgrading to 3.12 works as expected. Using Blender 4.0
<img width="327" alt="Screenshot 2024-03-26 at 21 52 43" src="https://github.com/nutti/Screencast-Keys/assets/25990657/44102b83-41ca-4bba-ba46-a539d5d4005c">

**Comment by nutti** [comment]
I think the unstable version fixes this issue.
Could you try it by installing manually?
https://github.com/nutti/Screencast-Keys/blob/master/docs/installation.md#support-version

**Comment by zhang-chongxiang** [comment]
> I think the unstable version fixes this issue. Could you try it by installing manually? https://github.com/nutti/Screencast-Keys/blob/master/docs/installation.md#support-version

Now it can display normally, thank you nutti!
