### ISSUE TITLE
Ccannot show the second key in Blender 4.1

### ISSUE THREAD

**Issue by lucidream** [nutti/Screencast-Keys#198]
### System Information
  
* OS: [Windows 10]
* Blender version: [4.1]
* Add-on version: [3.13]

### Expected behavior
Showing the two keys I pressed consecutively.

### Description about the bug**
The addon didn't show the second key I pressed, e.g the Z key if I pressed R-Z to rotate in the Z axis.

### Screenshots/Files [Optional]  
![Snipaste_2024-03-31_15-32-59](https://github.com/nutti/Screencast-Keys/assets/16292175/0bce9462-7b8c-443f-8262-4cca90251bb3)

### Additional comments [Optional]
The addon worked properly in Blender 4.0.3
![2](https://github.com/nutti/Screencast-Keys/assets/16292175/dba23e62-5026-4bf1-aa46-8659456680f0)

**Comment by nutti** [comment]
This issue is solved by the "get events aggressively" support on Blender 4.1.

058850d93c3c152771e8b7eab16a852e2e892180
