### ISSUE TITLE
It causes an infinite increase in the size of the preferences file

### ISSUE THREAD

**Issue by dkpress** [nutti/Screencast-Keys#201]
### System Information
  
* OS: Windows 10
* Blender version: [3.6~4.1]
* Add-on version: [3.13]

### Description about the bug**

As long as the "Screencast Keys" is enabled, it causes the size of Blender's preferences file “userpref. blend” to keep growing, even if I open Blender and close it right away, each time it increases in size by 98kb.

This problem has existed from version 3.6 to the current version 4.1

**Comment by nutti** [comment]
@dkpress 

Same as #195 .
Please install unstable version for now.
