### ISSUE TITLE
Screencast-Keys is not showing the number keys / version 3.13 will not work at all

### ISSUE THREAD

**Issue by donniebergh** [nutti/Screencast-Keys#202]
### System Information
  
* OS: OSX 14.4.1
* Blender version: [4.1.0]
* Add-on version: [3.12 also 3.13]

### Expected behavior

*The behavior you expect about the feature you reported.*

Screencast-Keys is not showing my number keystrokes functions such as a Scale or Grab

### Description about the bug**

*The description about the bug.*

With Screencast-Keys 3.12 turned ON - when I perform something like a scale s10 - the S is displayed but not the 10 - On version 3.13 Noting gets displayed - not even the S 

When I perform a grab such as GX10 - only the G is displayed - the X10 is missing 

### Screenshots/Files [Optional]  

*It is good to solve the bug if you attach the screenshots or .blend file.*

Here I'm using 3.12 and scaled the cube by 10 - s10 (Note the Shift-Control opens my screen capture utility)

<img width="1792" alt="image" src="https://github.com/nutti/Screencast-Keys/assets/52159256/9c03e0c3-3465-4e07-add2-91913a3475fc">

Here I'm using 3.13 - I scaled the cube by 5 - I entered s5 and nothing is displayed
<img width="1920" alt="image" src="https://github.com/nutti/Screencast-Keys/assets/52159256/5b55b4ab-c4ea-4433-8309-589e528c6385">

### Additional comments [Optional]

The bug happens on both of my two MACs - One has an Intel CPU and the other has a Mac Silicon M1 CPU.

**Comment by nutti** [comment]
@donniebergh 

Same as #198 
Please install the unstable version for now.
https://github.com/nutti/Screencast-Keys/blob/master/docs/installation.md

**Comment by donniebergh** [comment]
I have tried that version. I also tried it again today - it will not install.

-Donnie

**Comment by nutti** [comment]
@donniebergh 

Did you turn on the **Get Event Aggressively** checkbox?

**Comment by donniebergh** [comment]
I did in the 3.12 install. There was no change - I still id not get the number keys. But I did get number keys one time on the very first test of Scaling after a re-stall. And then never again.

Also when I changing the 3d view 1,3,7 I do get the number keys displayed..

The 3.13 and unstable do not appear in the Blender add Ons - the install fails without any messages. So there is no way set Get Event Aggressively.

**Comment by nutti** [comment]
@donniebergh 

Could you show me the add-on directory?
I think your installation seems incorrect.

**Comment by donniebergh** [comment]
￼



￼

**Comment by nutti** [comment]
@donniebergh 

It seems that you failed to upload the image.
Could you check it from GitHub issue page?
https://github.com/nutti/Screencast-Keys/issues/202

**Comment by donniebergh** [comment]
Oops - replied to the e-mail! - Here you go:

![Blender4 1](https://github.com/nutti/Screencast-Keys/assets/52159256/98439c1b-c2df-48b4-a658-e3665046ffa5)
![Screencast-Keys-maste](https://github.com/nutti/Screencast-Keys/assets/52159256/e1d9023b-7249-4982-ab63-80e0bee63b10)

**Comment by nutti** [comment]
@donniebergh 

Ah, installation process is incorrect.
You need to install manually by following below instruction.
https://github.com/nutti/Screencast-Keys/blob/master/docs/installation.md#1-download-zip-archive-from-below-links-1

**Comment by donniebergh** [comment]
I downloaded 3.12. Performed the manual install and I did not get any displays.

The I realizes you want me use the "unstable" - ! it works.

**Comment by donniebergh** [comment]
I have Screencast-Keys working to my satisfaction!

Thank you for your help.

I'm closing the issue as resolved.

**Comment by nutti** [comment]
Good hear that.
