### ISSUE TITLE
Add-Ons change to Extension tab preferences.

### ISSUE THREAD

**Issue by mac4kent** [nutti/Screencast-Keys#205]
Blender 4.2.0 Alpha May 20, 2024
There have lot and lot change more feature and just work on your Screencast Key after finish Alpha to be BETA come soon.
There is no long word "Add-ons" and change to "Extension"
I let you know and information to you.

<img width="3200" alt="image" src="https://github.com/nutti/Screencast-Keys/assets/4253305/834c4343-9740-4c28-a85b-1bafea1aee60">

**Comment by nutti** [comment]
We will release Screencast Keys v4.0 after Blender 4.2.0 is released.
v4.0 will not have backward compatibility with the older version.

**Comment by mac4kent** [comment]
Yes I agree. No problem

**Comment by nutti** [comment]
Screencast Keys add-on is now approved to register at extensions.blender.org.
https://extensions.blender.org/approval-queue/screencast-keys/

We can successfully close this issue now.
