### ISSUE TITLE
Addon Turns Off When Switching Workspaces

### ISSUE THREAD

**Issue by ryankingart** [nutti/Screencast-Keys#206]
### System Information
  
* OS: Linux Mint Cinnamon
* Blender version: 4.1.1
* Add-on version: 3.14.0

### Expected behavior

When I switch to a different workspace, like from layout, to shading, to compositing, and so on, the screencast keys are turned off. I have to re-turn them on every time I switch to a different workspace in Blender. It would be really nice if the addon stayed on in each editor and workspace. Thanks!

**Comment by nutti** [comment]
Same as #69.

@ryankingart 

Please check the solution.
https://github.com/nutti/Screencast-Keys/issues/69#issuecomment-911626292

**Comment by ryankingart** [comment]
Thanks, that fixed the issue!
