### ISSUE TITLE
Feature Request: upload Screencast-Keys to the Blender Extension Platform 

### ISSUE THREAD

**Issue by xan2622** [nutti/Screencast-Keys#208]
Hi.

As you may already know, add-ons and themes can now be uploaded to the [Blender Extension Platform](https://extensions.blender.org/).

Related topics: 
https://extensions.blender.org/about/
https://code.blender.org/2024/05/extensions-platform-beta-release/
https://devtalk.blender.org/t/changes-to-add-on-and-themes-bundling-4-2-onwards/34593

I think it would be really cool (and convenient) if your add-on was available on the Blender Extension Platform. It would help Blender users discover and download your add-on more easily. 

Could you please consider uploading your add-on on this new website?
Thanks in advance.

**Comment by nutti** [comment]
We have already uploaded there.

https://extensions.blender.org/add-ons/screencast-keys/
