### ISSUE TITLE
Display keys in modal state

### ISSUE THREAD

**Issue by wesleyvanitou** [nutti/Screencast-Keys#21]
**Display the key when a modal state is activated**
*If you press g to move an object, you enter in a modal state where you can after that press s to scale r to rotate and so on but it doesn't show it. It will be nice to have that.*

**Are you willing to contribute about this feature.**  
*Monetarily Yes*

**Screenshots**
https://i.imgur.com/88KqCsh.gif

**Additional comments**
*Good job keep it up ;)*

**Comment by nutti** [comment]
@wesleyvanitou 

Thanks for your report.
This feature is already in [v3.1](https://github.com/nutti/Screencast-Keys/releases/tag/v3.1).
But I recommend you to use [newest version](https://github.com/nutti/Screencast-Keys/archive/master.zip) which fixed a bug related this feature.

Please also see [this issue](https://github.com/nutti/Screencast-Keys/issues/6).
Thanks.
