### ISSUE TITLE
With screencast keys enabled it breaks running Blender headlessly

### ISSUE THREAD

**Issue by BIMvoice** [nutti/Screencast-Keys#210]
### System Information
  
* OS: Windows
* Blender version: 4.1.1
* Add-on version: 3.14.0

It stops other add-ons from working, yielding an error.

**Comment by nutti** [comment]
@BIMvoice 

Sorry, I could not catch your issue.
Could you explain your issue more detail?

**Comment by BIMvoice** [comment]
Having Screencast Keys add-on enabled is preventing another add-on from working properly. The main dev of that tool told me that this is happening: screencast keys enabled it breaks running blenderBIM headlessly. I don't know what it means, but the 2 addons cannot co-exist.

**Comment by Andrej730** [comment]
I've met errors running blender in background with screencast keys enabled (submitted a fix in #212) but they don't really interrupt any other addons, they just pop up in the console and can be ignored.

**Comment by nutti** [comment]
@BIMvoice 

Could you show me the process step by step to reproduce the error?
I'm not familiar with blenderBIM, so it is difficult to reproduce for me.

**Comment by nutti** [comment]
@BIMvoice Any update about this issue?

**Comment by nutti** [comment]
Close this issue due to no reaction.
Please ping us if there is still some issue.
