### ISSUE TITLE
Traceback upon enable

### ISSUE THREAD

**Issue by Viola-Case** [nutti/Screencast-Keys#211]
### System Information
  
* OS: Windows 11
* Blender version: 4.1.1
* Add-on version: 3.14.0

### Expected behavior

*The behavior you expect about the feature you reported.*

### Description about the bug**

On enabling, received traceback. details in screenshot.

### Screenshots/Files [Optional]  

![image](https://github.com/user-attachments/assets/b575d1df-0f7b-4154-ab97-cb5f2e90d40d)
*It is good to solve the bug if you attach the screenshots or .blend file.*

### Additional comments [Optional]

Just downloaded the addon today. Not sure why it's erroring like this.

**Comment by nutti** [comment]
Same as https://github.com/nutti/Screencast-Keys/issues/64#issuecomment-882070697.
Please reinstall add-on or blender.

**Comment by nutti** [comment]
Any update?

**Comment by nutti** [comment]
Close this issue due to no reaction.
