### ISSUE TITLE
Gives error when I try to check enable

### ISSUE THREAD

**Issue by PeanutButterGaming** [nutti/Screencast-Keys#213]
### System Information
  
* OS: [Windows 11 Home]
* Blender version: [UPBGE 0.36.1  Blender 3.6.2 source]
* Add-on version: [3.14.0+]

### Expected behavior

to work

### Description about the bug**

gives python error

![image](https://github.com/user-attachments/assets/cd1fb682-d411-4bb1-92b6-b399a9be1744)

*It is good to solve the bug if you attach the screenshots or .blend file.*

**Comment by nutti** [comment]
@PeanutButterGaming 

Is it possible to restart or reinstall Blender and add-on?

**Comment by nutti** [comment]
@PeanutButterGaming 

Any update?

**Comment by nutti** [comment]
Close this issue due to no reaction.
This issue has already solution, please see [FAQ](https://github.com/nutti/Screencast-Keys/blob/master/docs/faq.md#failed-to-install-this-add-on).
