### ISSUE TITLE
I can't install the addon

### ISSUE THREAD

**Issue by biiizunga** [nutti/Screencast-Keys#214]
Hello,

I'm encountering an issue with the keystroke display addon in Blender 4.0.2. I followed the standard installation procedure:

I downloaded the .zip file and extracted it to a folder.
In Blender, I went to Preferences > Add-ons and clicked "Install" to add the addon.
The addon appears in the Add-ons list, but when I try to activate it, I receive the following error message:
arduino
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 401, in enable
    mod.register()
  File "C:\Users\Giovana\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\screencast_keys\__init__.py", line 143, in register
    bpy.utils.register_class(preferences.DisplayEventTextAliasProperties)
ValueError: register_class(...): already registered as a subclass 'DisplayEventTextAliasProperties'
It seems the addon is attempting to register a class that is already registered, but I do not have anny add-on of this type installed. I'm not sure how to resolve this. Could you please provide assistance?

Thank u

**Comment by nutti** [comment]
@biiizunga 

See [FAQ](https://github.com/nutti/Screencast-Keys/blob/master/docs/faq.md#failed-to-install-this-add-on).
This is a common issue and can be solved by restarting/reinstalling Blender or reinstall this add-on.

**Comment by nutti** [comment]
@biiizunga 

Any update?

**Comment by nutti** [comment]
Close this issue due to no reaction and the solution is identified as FAQ.

**Comment by biiizunga** [comment]
> Close this issue due to no reaction and the solution is identified as FAQ.

Sorry for the delay, but it worked! Thank u so much :D
