### ISSUE TITLE
Clicking too fast on the "screencast keys" checkbox causes it not to activate

### ISSUE THREAD

**Issue by valeofhearts** [nutti/Screencast-Keys#215]
### System Information
  
* OS: [e.g. Windows]
* Blender version: 4.2.1 [e.g. 2.79]
* Add-on version: 4.0.0 [e.g. 5.2]

### Expected behavior
Flip to TRUE every time checkbox is clicked.

*The behavior you expect about the feature you reported.*

Clicking too fast on the "screencast keys" checkbox while it is FALSE causes it not to activate.

**Comment by nutti** [comment]
@valeofhearts 

> Clicking too fast on the "screencast keys" checkbox

I did not understand the purpose of this use-case.
Fast clicking the checkbox obviously seems not to activate because activating process is heavier than deactivation.

**Comment by nutti** [comment]
@valeofhearts 

Any comment about this?

**Comment by nutti** [comment]
Close this issue due to no reaction and the misuse of this add-on.
