### ISSUE TITLE
Semi-Transparent background

### ISSUE THREAD

**Issue by haseebahmed295** [nutti/Screencast-Keys#216]
Is there any way to make the background semi transparent.

**Comment by nutti** [comment]
@haseebahmed295 

Maybe there is a bug.
Actually, you can specify the background color and transparency from Screencast Keys panel.
But it does not work well.

**Comment by haseebahmed295** [comment]
well it may be due to gpu state being not set correctly .I myself had this issue so I tried checking addon but also does not worked . For my case setting the gpu state to alpha did the trick
`gpu.state.blend_set('ALPHA')  # Enable alpha blending`

**Comment by nutti** [comment]
This issue is now fixed.
Thank you for reporting this @haseebahmed295
