### ISSUE TITLE
Mouse button clicks not registering properly

### ISSUE THREAD

**Issue by badbunny-uk** [nutti/Screencast-Keys#217]
### System Information
  
* OS: Windows 11 Pro and Windows 10 Pro
* Blender version: 4.2.1
* Add-on version: 4.0.0 (installed via extensions)

### Description about the bug**

In 4.2 mouse button clicks are not consistently registering on the GUI.
Also when you move the mouse they always disappear.

So for example if you rotate with the MMB, the MMB icon disappears as soon as you move the mouse, whereas In 4.1 (with addin version 3.12.0) while I'm holding the MMB, the MMB icon is constantly shown until I release it.

In 4.2 it seems only about half of the mouse button single clicks are registering, whereas in 4.1 every click is registered.

**Comment by badbunny-uk** [comment]
Another observation... if I enable Event History+Hold Status, then every mouse button click is registered, both in the GUI and the text. But if I change that to the default Hold Status, then only about half of the mouse clicks show in the GUI.  However when moving the mouse, the button status immediately clears when moving the mouse for both of those options.

**Comment by nutti** [comment]
This issue is now fixed.

> if I enable Event History+Hold Status, then every mouse button click is registered, both in the GUI and the text. But if I change that to the default Hold Status, then only about half of the mouse clicks show in the GUI.

This is the expected behavior.
Check "Show Mouse Event" option in tutorial.
https://github.com/nutti/Screencast-Keys/blob/master/docs/tutorial.md#show-mouse-events
