### ISSUE TITLE
Button presses not showing in GUI

### ISSUE THREAD

**Issue by badbunny-uk** [nutti/Screencast-Keys#218]
### System Information

OS: Windows 11 Pro and Windows 10 Pro
Blender version: 4.2.1
Add-on version: 4.1.0 (installed via extensions)
Description about the bug**

In 4.2 mouse button clicks are not all showing in the GUI.
Also when holding a mouse button down they always show unpressed as soon as you move the mouse.
I've tried the 4.1.0 update (uninstalled 4.0.0 then installed 4.1.0), but no change.
I've attached two screen recordings showing the issues...

This video shows how mouse button press state is not persistent, ie as soon as I move the mouse the state disappears and shows no button being pressed...
https://github.com/user-attachments/assets/085242ba-f06c-4522-8f43-85225c3ac598

This video shows how the 'Hold Status' and 'Event History + Hold Status' setting seems to influence whether all button presses are being displayed in the GUI...
https://github.com/user-attachments/assets/a51040fa-fbef-48b6-9988-c86623092e90

**Comment by nutti** [comment]
> This video shows how mouse button press state is not persistent, ie as soon as I move the mouse the state disappears and shows no button being pressed

This issue has already fixed. But fixed patch is not released yet.
If you want to use this add-on with the patch, you can use unstable version instead for now.
https://github.com/nutti/Screencast-Keys/blob/master/docs/installation.md#manual-install

> This video shows how the 'Hold Status' and 'Event History + Hold Status' setting seems to influence whether all button presses are being displayed in the GUI

Again, this is a correct behavior.
https://github.com/nutti/Screencast-Keys/blob/master/docs/tutorial.md#show-mouse-events

**Comment by nutti** [comment]
> This video shows how the 'Hold Status' and 'Event History + Hold Status' setting seems to influence whether all button presses are being displayed in the GUI

I understood that the main issue of this is the inconsistency among "Show Mouse Event" options.
I fixed this issue now.
