### ISSUE TITLE
Error print when in background mode

### ISSUE THREAD

**Issue by venomgfx** [nutti/Screencast-Keys#219]
### System Information
  
* OS: macOS
* Blender version: 4.4a
* Add-on version: 4.0.1

### Description about the bug**

When running Blender on background mode, this add-on prints an error:

```
  File "/Users/user/Library/Application Support/Blender/4.4/extensions/blender_org/screencast_keys/gpu_utils/shader.py", line 52, in register_shaders
    gpu.platform.backend_type_get() != 'OPENGL':
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SystemError: GPU functions for drawing are not available in background mode
```

It seems harmless and Blender continues to work well, but it adds noise.

Could you please add a check if Blender is being run in the background? You can do so by checking for `bpy.app.background`. 

Thank you! Love this add-on.

**Comment by nutti** [comment]
@venomgfx 

I think this is fixed by #212 .
Does this error also exist in the latest version?

**Comment by nutti** [comment]
@venomgfx Any update?

**Comment by nutti** [comment]
Close this issue due to no reaction.
