### ISSUE TITLE
Screencast-Keys_v3.1 can't work in Blender v2.83

### ISSUE THREAD

**Issue by zgkony** [nutti/Screencast-Keys#22]
Hi Nutti,

Screencast-Keys_v3.1 can't work in Blender v2.83,pls fix it,thanks!

**Comment by nutti** [comment]
@zgkony 

v3.1 will be crashed the Blender v2.83 because of #18 .
We will release v3.2 in a few day, this issue will be solved.

**Comment by zgkony** [comment]
Thanks!!!

**Comment by nutti** [comment]
@zgkony 

Now, this issue is fixed.
I will release v3.2 in a few days, but you can try it from master branch (https://github.com/nutti/Screencast-Keys/archive/master.zip) if you want.

**Comment by zgkony** [comment]
@Nutti,

Thanks！！！

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
