### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by jay-b** [nutti/Screencast-Keys#23]
**System Information**
  
* OS: MacOS 10.13.6
* Blender version: 2.8.3.0
* Add-on version: 3.2

**Expected behavior**  
Installs.

**Description about the bug**  
Blender reports it has installed, the folder tree exists in Application Support, etc. The plugin doesn't show in Blender prefs.

**Screenshots/Files** [Optional]  
![Screen Shot 2020-06-13 at 11 27 59](https://user-images.githubusercontent.com/900423/84566434-ff522900-ad68-11ea-96df-00a0c7e0140d.jpg)
![Screen Shot 2020-06-13 at 11 23 37](https://user-images.githubusercontent.com/900423/84566441-12fd8f80-ad69-11ea-8a57-6301b1646e82.jpg)

**Additional comments** [Optional]
Edit: typos.

**Comment by nutti** [comment]
@jay-b 

Hi, I think your installation process is wrong.
Please check the [installation docs](https://github.com/nutti/Screencast-Keys/blob/master/docs/installation.md).
If you try to use unstable version, you can't install this add-on directly.

**Comment by jay-b** [comment]
Hi, sorry not following what you mean. 3.2 isn't an unstable verison, right? I had also tried manually placing the unzipped files in:

/Users/<username>/Library/Application Support/Blender/<blender_version>/scripts/addons

It just doesn't show up in Blender.

**Comment by jay-b** [comment]
Ah, I see what you mean now. I've sorted it by moving the 'screencast_keys' from the src folder, into the addons folder. Thanks!

**Comment by nutti** [comment]
@jay-b 

Thanks for your feedback!
I'm pleasure to fix your issue.

If you have any further issue about this, feel free to open new issue or reopen this issue.
