### ISSUE TITLE
RZ180 doesnt work

### ISSUE THREAD

**Issue by brainbox78** [nutti/Screencast-Keys#24]
Hallo dear Devs,

this plugin is amazing and i love it but i would like to ask you if it is possible to implement the possibility to show shortcuts like RZ180. I tried it with Version 3.2 and it doesnt work for me. Everything else just works fine but when i want to showcase the keystroke pattern R Z 180 (rotate object around the Z axis to 180°) then it just shows R Z but no numbers or sometimes it shows R Z 0 instead of R Z 1 8 0.

Thank you for this great plugin

**Comment by brainbox78** [comment]
Shortcuts like  S X (scale in x axis) also doesnt work

**Comment by nutti** [comment]
@brainbox78 

I think you didn't switch on [Get Event Aggressively](https://github.com/nutti/Screencast-Keys/blob/master/docs/tutorial.md#get-event-aggressively).
If you want to show shortcuts in modal state, you need to enable this option.

**Comment by brainbox78** [comment]
well i switched on Get Event Aggressively but that doesnt helped. I will make a video and post a link to it.

**Comment by brainbox78** [comment]
Sorry guys i found out the problem. The script works fine. It was incompatible with one of my own scripts. You can close the case. thank you for the help

**Comment by nutti** [comment]
Good to hear about it.
If you have any other issues, feel free to open new issue.
