### ISSUE TITLE
The key and mouse buttom display is gone if the timeline gets larger on the screen

### ISSUE THREAD

**Issue by EaryChow** [nutti/Screencast-Keys#27]
**System Information**
  
* OS:  Windows 10
* Blender version: 2.90
* Add-on version: 3.2.0

**Expected behavior**  
*The behavior you expect about the feature you reported.*
The key and mouse buttom display should always be there, so that it will show whatever key I pressed at anytime. But now there is a problem.

**Description about the bug**  
The display is gone if you enlarge the timeline and wait a bit. It will come back after your click again. But all the keys you pressed before you click again will not be displayed. 

**Screenshots/Files** [Optional]  
*It is good to solve the bug if you attach the screenshots or .blend file.*
This is a video in a zip file (because GitHub does not support video files):
[Screencast Keys Timeline Bug.zip](https://github.com/nutti/Screencast-Keys/files/5143565/Screencast.Keys.Timeline.Bug.zip)

**Additional comments** [Optional]

**Comment by nutti** [comment]
@EaryChow 

Nice catch!
I found this is a problem of drawing procedure, and fixed it.

You can try fixed version if you want.
https://github.com/nutti/Screencast-Keys/blob/master/docs/installation.md#installation

I'll close this issue.
Please let me know if you have any other issue.
Thanks.
