### ISSUE TITLE
in blender 2.8 not works 

### ISSUE THREAD

**Issue by shinethorns** [nutti/Screencast-Keys#3]
![2019-01-19_22h07_43](https://user-images.githubusercontent.com/13419756/51427832-0853cf00-1c37-11e9-8ad8-ba24874e082c.jpg)

**Comment by nutti** [comment]
Close this issue for now. Please make issue if another issue araised.

**Comment by MathieuDijkstra** [comment]
in blender the start buton to start the screen cast is not showing up:
 press the Start Display button under Screencast Keys in N panel. 
the combination keys do work [shift]+[alt]+[c]

somthing missing
![screen cast menu dont show up](https://user-images.githubusercontent.com/21957692/54473363-3852c500-47d7-11e9-9c63-0af2dd2ee03c.PNG)

**Comment by MathieuDijkstra** [comment]
![blender version](https://user-images.githubusercontent.com/21957692/54473382-57e9ed80-47d7-11e9-97e1-19f3795f2f67.PNG)

**Comment by nutti** [comment]
@MathieuDijkstra 

Could you make another issue?
Your issue is not related to the original issue.
