### ISSUE TITLE
stops blender from autosaving

### ISSUE THREAD

**Issue by DragonZealot** [nutti/Screencast-Keys#31]
**System Information**
  
* OS: [e.g. Windows]
* Blender version: [e.g. 2.79]
* Add-on version: [e.g. 5.2]

**Expected behavior**  
*The behavior you expect about the feature you reported.*

**Description about the bug**  
*The description about the bug.*

**Screenshots/Files** [Optional]  
*It is good to solve the bug if you attach the screenshots or .blend file.*

**Additional comments** [Optional]

**Comment by nutti** [comment]
@DragonZealot 

This is a limitation of this add-on.
In modal mode, auto saving feature is automatically disabled in Blender.
This is one of the frequently asked question, so I will add this note to the document.
