### ISSUE TITLE
overlays still bouncing

### ISSUE THREAD

**Issue by 3diuk** [nutti/Screencast-Keys#34]
Hi, i've added a comment to the old report, but raising a new one  just in case that doesnt raise a notification.

The bug is still there if origin is set to window.  and even if set to region the overlays start bouncing again if you open a new workspace tab.  Additionally if you have two 3d viewports open in one workspace, then if you move your mouse from one viewport to the other and then back, the bouncing happens initially when the mouse travels across a parameters panel.

**Comment by nutti** [comment]
I will close this issue because of duplication.
Please reopen the issue if the patch does not work.
