### ISSUE TITLE
Choice between Sidebar panel and Viewport Overlay

### ISSUE THREAD

**Issue by Michaelknubben** [nutti/Screencast-Keys#35]
**Description about the feature**  
As we all know, the Sidebar can get overloaded with hard to read tabs, and Blender now has an easily accessible feature for Viewport Overlays. I think this fits there, and would love to have the option to display it in the Viewport Overlay dropdown. Personally I don't see a reason for all of the features from the current panel to be displayed there, I would set the colour, font size etc. in the addon options.

**Are you willing to contribute about this feature. (Yes/No)**  
Yes: but I'm not a developer. I would be open to making mockups and testing the feature though.

**Screenshots** [Optional]  
*It is good to understand the features if you attach the screenshotsfile.*
The panel as it is now:
![image](https://user-images.githubusercontent.com/27723800/96249448-7b75ab00-0fad-11eb-85be-72751cccd4f1.png)
Where I'd want to see it instead:
![image](https://user-images.githubusercontent.com/27723800/96249476-8597a980-0fad-11eb-8f32-e5ea9de9c291.png)

**Additional comments** [Optional]

I'm a teacher since very recently, so I'd like to thank you for keeping this addon up to date!

**Comment by nutti** [comment]
@Michaelknubben 

Thanks for your request.
It seems interesting.

If possible, I would like to know the add-ons which realizes this improvement.

**Comment by nutti** [comment]
@Michaelknubben 

OK, now I got how to add UI to viewport overlay.

![github_20201006](https://user-images.githubusercontent.com/1463952/96258516-1777d480-0ff7-11eb-8020-7e9a1ed5ff44.png)

You can also this feature from below link.
https://github.com/nutti/Screencast-Keys/archive/spike_35.zip

Do you have any good idea for improving this UI?

**Comment by Michaelknubben** [comment]
Great, glad you figured it out!
Honestly? I'd just get rid of all features except for the toggle (so turning it on or off), and have all other features available in the addon preferences. Possibly you could also list the colour after it, so it'd be like Wireframe's Toggle and Slider. Another option is to have a cogwheel icon behind it that opens the addon preferences directly? I just really want to advise against listing all of this stuff in that menu.

**Comment by Michaelknubben** [comment]
Oh, and if you _do_ list anything else, I think it'd be good if you'd make it invisible until the toggle is on. An example of this behaviour is in Mesh Check (BGL Edition), a free addon.

**Comment by nutti** [comment]
@Michaelknubben 

Thanks for your feedback.
I almost implemented this feature now.

Finally, I introduced new overlay menu for Screencast Keys.

![github_20201018](https://user-images.githubusercontent.com/1463952/96367668-2e9afb80-118a-11eb-81c4-48d2d88324d2.png)

I think it is good for separating from exists overlay menus.
This feature is now available in testing branch.
Could you try this?

https://github.com/nutti/Screencast-Keys/archive/spike_35.zip

**Comment by Michaelknubben** [comment]
Like I said before, I really do think the settings belong in the addon preferences, and I see no reason to create a new menu. If every addon does that, we're right back to 2.7x's problems with the T panel!
You're ofcourse free to disagree and steer your own course, but I'll probably use Pie Menu Editor to create my own button somewhere and take it out of the sidepanel.

**Comment by nutti** [comment]
Your advise was introducing a overlay menu on header for Screencast keys.
Does my understanding mistake?

If you have any mock up UI, it helps me a lot.

**Comment by nutti** [comment]
@Michaelknubben 

Perhaps, you think the UI as follows.

![github_20201019](https://user-images.githubusercontent.com/1463952/96426725-927bfd80-1238-11eb-86c0-a6ca861dcf75.png)

This new UI does not introduce any new Menu.
You can switch on/off previous Panel on Sidebar and new UI.

**Comment by Michaelknubben** [comment]
Exactly, that's what I meant! Sorry for the confusion, I'll make sure to include a mockup next time.

**Comment by nutti** [comment]
This feature is now merged to master branch.

@Michaelknubben 

Thanks for your help!

**Comment by Michaelknubben** [comment]
Hey Nutti, I tested this (in 2.91) and found an issue:
![afbeelding](https://user-images.githubusercontent.com/27723800/101981998-0d79f700-3c71-11eb-9f41-d2bc3c9c673e.png)
This is with 'Overlay' enabled in the settings, which only adds a blank space at the bottom, but I see no button!

I've tried restarting, but no change.

Is there something I can do to help you fix this?

**Comment by nutti** [comment]
@Michaelknubben 

Sorry, I haven't noticed your issue.
I can find this issue from the another issue.
The bug has already fixed, and you can try the unstable version which merges the fixed patch.

If you have any further issue about this feature, please create new issue.
Thanks.
