### ISSUE TITLE
Second keystroke after G,S,R isn't shown

### ISSUE THREAD

**Issue by hapit** [nutti/Screencast-Keys#37]
**System Information**
  
* OS: MacOS
* Blender version: 2.90.1
* Add-on version: v3.3

**Expected behavior**  
*When I transform an object and then constrain it to an axis. The Key for the axis isn't shown.*

**Description about the bug**  
*Example: Select object, press G, press X -> the X isn't shown.*

**Screenshots/Files**
*It happens with the default startup file.*

**Comment by nutti** [comment]
Please see [FAQ](https://github.com/nutti/Screencast-Keys/blob/master/docs/faq.md).
