### ISSUE TITLE
Error On Deleting Objects

### ISSUE THREAD

**Issue by H-e-ro** [nutti/Screencast-Keys#38]
**System Information**
OS: Windows 10
German Keyboard
Blender 2.91.0 (fresh released)
Addon Version (actual)

**Expected behavior**  
Delete object and display "Delete".

**Description about the bug**  
Use that tool with Blender 2.91.0 (fresh released). On deleting objects by pressing "Delete", i get an error.

**Screenshots/Files** [Optional]  
![erroro](https://user-images.githubusercontent.com/75077979/100412791-de129a00-3075-11eb-9559-619398565824.jpg)

**Additional comments** [Optional]

**Comment by H-e-ro** [comment]
After restarting my computer, the bug is gone. Everything works fine.  This probably affects only fresh installs.

**Comment by nutti** [comment]
@H-e-ro 

Is this still problem?
If so, could you give me add-on version.

**Comment by H-e-ro** [comment]
Thereis an other issue. Blender crashes by using Screw-Tool with active Screencast-Keys Addon.

**Comment by nutti** [comment]
@H-e-ro 

Could you give me add-on version and detail logs?
I think your issue relates to the old issue which is already fixed.

**Comment by H-e-ro** [comment]
Use 3.0.0. How to get a detail log from SK?

**Comment by nutti** [comment]
@H-e-ro 

Ah, v3.0 is the exact version which will cause your issue.
Could you try v6.4 instead?

https://github.com/nutti/Magic-UV/releases/tag/v6.4

**Comment by H-e-ro** [comment]
Thats better. Will try in a few minutes. First you linked Magic-UV, was irritated. :)

**Comment by H-e-ro** [comment]
Works like a charm!!! Thank you and also for your tools! :)

**Comment by nutti** [comment]
@H-e-ro 

Thanks.
I'm pleasure to solve your issue :)
