### ISSUE TITLE
“Caps Lock” keypress causes the addon crash

### ISSUE THREAD

**Issue by camtofu** [nutti/Screencast-Keys#39]
**System Information**
  
* OS: Win10 x64 Home
* Blender version:  2.91.0
* Add-on version: 3.0.0

**Expected behavior**  
Though "Caps Lock" key plays no function in Blender, but its keypress should not cause error.

**Description about the bug**  
When "Caps Lock" key pressed, the addon "Screencast Keys" crash and prompt error msg,

> Python: Traceback (most recent call last):
>   File "Z:\blender_2.91\2.91\scripts\addons_contrib\screencastkeys\ops.py", line 587, in modal
>     event_type = EventType[event.type]
>   File "Z:\blender_2.91\2.91\python\lib\enum.py", line 352, in __getitem__
>     return cls._member_map_[name]
> KeyError: ''
> 
> location: <unknown location>:-1
> 
> 

**Additional comments** [Optional]
When addon crashed, deactivate then activate the addon in N-panel will recover from the error.

**Comment by nutti** [comment]
This issue has already fixed since v3.1.
c.f. #7
