### ISSUE TITLE
Wrong alignment when "Origin" set to "Window"

### ISSUE THREAD

**Issue by camtofu** [nutti/Screencast-Keys#40]
**System Information**
  
* OS: Windows 10 x64 Home
* Blender version: 2.91
* Add-on version: 3.4.0
* Graphic Card: Nvidia 310M, 1366x768

**Description about the bug**  
1. When "Origin" option set to "Windows", and "Align" option set to "Center", the keys prompt is displayed at right border of current Blender window.
2. ... and "Align" option set to "Right", the keys prompt is missing from screen.

**Screenshots/Files** [Optional]  
[https://pasteboard.co/JGqWW7l.jpg](url)

**Additional comments** [Optional]
My graphic card is outdated, I wonder if this is the culprit for this error.

**Comment by nutti** [comment]
@camtofu 

Unfortunately, I could not reproduce this issue in my environment.
Is it possible to test without GPU?

BTW, blender does not support 300 series officially.
https://www.blender.org/download/requirements/
So, I recommend you to use newer graphic card.

**Comment by camtofu** [comment]
@nutti 
I corrected a typo in my former report,
Foremer below,
> 2. ... and "Align" option set to **"Center"**, the keys prompt is missing from screen.

Corrected below,

> 2. ... and "Align" option set to **"Right"**, the keys prompt is missing from screen.

Could you please give one more test?

Have a good day.

**Comment by nutti** [comment]
@camtofu 

Yeah, I have already tried them.
But I found there is no issue.

**Comment by camtofu** [comment]
Then I close this report now. Thank you.

**Comment by nutti** [comment]
@camtofu 

In my environment, your patch does not work correctly.
From my investigation, `window.width` does not return correct value in my environment.
I'm not sure whether this is blender's bug or specification.
But your patch looks good to me.

I'll check this patch in other environment.
If this patch is valid, I'll approve this patch.
If possible, I would like you to make a pull request to include this patch to this project.
Of course, I will add your name to the author of this add-on.

**Comment by MjTs140914** [comment]
Can overlay active if blender statup? 

I mean when I open the blender, this tool is immediately active and no need to activate it again, can you provide that option?

I use Blender 2.9

**Comment by nutti** [comment]
@MjTs140914 

Please do not post your issue which is not related to the original issue.
Instead, you need to make new issue.

Also, your issue is already found [FAQ](https://github.com/nutti/Screencast-Keys/blob/master/docs/faq.md).
Please see it why this feature is not supported in this add-on.

**Comment by MjTs140914** [comment]
@nutti I'm really sorry.

**Comment by nutti** [comment]
@camtofu 

I confirmed that your patch is valid in other environment.
And I also posted this problem to the D.B.O.
https://developer.blender.org/T84204

Anyway, your patch should be included in this project.
Is it possible to make a pull request?

Thanks for your great work!

**Comment by camtofu** [comment]
> Is it possible to make a pull request?
> 
@nutti

To be frank, I don't know how to pull request. I'm not a coder.

It would be very kinde of you to include my patch into the code. Thank you.

**Comment by nutti** [comment]
@camtofu 

OK. Then I will merge it.
If you don't mind, I will add your name to the author and contributor.

* https://github.com/nutti/Screencast-Keys#project-authors
* https://github.com/nutti/Screencast-Keys/blob/48c82fcfedc79e27ecb4fc12825eea29cdc78280/src/screencast_keys/__init__.py#L24

If you want to do this, could you give me your name to be registered.

**Comment by camtofu** [comment]
> If you don't mind, I will add your name to the author and contributor.

@nutti 
Thank you very much but plz don't bother to do that.

**Comment by nutti** [comment]
@camtofu 

I merged your patch.
Thanks for your contribution!

I didn't add your name to the contribution list because of your wish.
Please do not hesitate if you change your mind.
