### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by louis1lal** [nutti/Screencast-Keys#41]
**Description about the feature**  
*The description about the feature. It is good to clear who will benefit with this feature.*
Just a quick message to say that the easiest way to install this add-on on OSX is to install it from Blender. Go to edit, addons, install addons, select the zip file then activate it and Blender will put the file where ever he wants. The path shown in the doc does not exist on my computer.

Great plugin! Thanks

**Are you willing to contribute about this feature. (Yes/No)**  

**Screenshots** [Optional]  
*It is good to understand the features if you attach the screenshotsfile.*

**Additional comments** [Optional]

**Comment by nutti** [comment]
The document is now updated.
Thanks for your advice @louis1lal !
