### ISSUE TITLE
An error occurred when calling when trying to measure an object with a tape measure.

### ISSUE THREAD

**Issue by AlexMcKonst** [nutti/Screencast-Keys#42]
- OS: [Windows 8]
- Blender version: [e.g. 2.9.1]
- Add-on version: [3,0,0]
- NVIDIA GeForce GTX 550 Ti

I activate the measurement mode. Your addon freezes. And stops working. Then you have to turn off and turn on your addon again. 
 
I wanted to take a measurement, but yours stops working when you call this function*
Screenshots/Files

![image](https://user-images.githubusercontent.com/26620124/103285164-63c79380-49ee-11eb-8d19-1911439ca963.png)
*It is good to solve the bug if you attach the screenshots or .blend file.*

**Comment by nutti** [comment]
This issue has already fixed since v3.1.
c.f. #7

**Comment by AlexMcKonst** [comment]
Thank you! Excuse for troubling!
