### ISSUE TITLE
Show constraints keys for an operation

### ISSUE THREAD

**Issue by DolphinDream** [nutti/Screencast-Keys#46]
When pressing G to grab/move something.. you can immediately press x/y/z (or shift + x/y/z) to control the moving constraints along various axes. Apparently the screencast keys add-on doesn’t seem to capture these key strokes? Is there a way to do so? 

Same is true for other operations (rotate, extrude etc) where constraints can be applied to the main operation by pressing other keys.

I’m not sure if this is a bug.. or perhaps a feature that would need to be added..l or maybe there is a setting already that I missed.

thanks

**Comment by nutti** [comment]
Please see the [FAQ](https://github.com/nutti/Screencast-Keys/blob/master/docs/faq.md).

**Comment by DolphinDream** [comment]
Apparently the **Get Event Aggressively** option is disabled and not able to turn neither in prefs or panel.

**Comment by nutti** [comment]
@DolphinDream 

**Get Event Aggressively** option is only supported in <=2.91.
I'm tackling to support 2.92 because Blender 2.92 was released recently.
If you want to try this option, you need to use Blender 2.91 for now.

**Comment by nutti** [comment]
@DolphinDream 

I have finished to support **Get Event Aggressively** now.
You can try this by using the [unstable version](https://github.com/nutti/Screencast-Keys/blob/master/docs/installation.md#1-download-zip-archive-from-below-links-1).
