### ISSUE TITLE
Blender 2.93 Alpha Add-one error screenkey

### ISSUE THREAD

**Issue by mac4kent** [nutti/Screencast-Keys#48]
**System Information**

MacOS 11.3 Beta (20E5196f)
Build Blender 2.93 Alpha
https://builder.blender.org/download/

Display (More space) See picture
![image](https://user-images.githubusercontent.com/4253305/110032844-7d869f00-7ced-11eb-8b1a-53bd249fb79f.png)

Version 3.4
@nutti nutti released this on Dec 19, 2020

**Expected behavior**  
*The behavior you expect about the feature you reported.*
Import button on Add-on then click [√] cause error see picture below of link

https://imgur.com/Ge9BdLb

**Comment by mac4kent** [comment]
Oh I see that wrong version 3.4.0. I did download 3.4.5 but you forget to update 3.4.0 change to 3.4.5
![image](https://user-images.githubusercontent.com/4253305/110034145-f9cdb200-7cee-11eb-8e81-b6137af53d55.png)

**Comment by nutti** [comment]
This relates to #45 .

Please use the master branch for now.
I will release v3.5 on this weekend.

**Comment by mac4kent** [comment]
Ok I will wait to see to get update 3.5 next week.

**Comment by nutti** [comment]
@mac4kent 

Thanks.
If you want to use this add-on, you can try to use the unstable version.
https://github.com/nutti/Screencast-Keys/blob/master/docs/installation.md#manual-install
