### ISSUE TITLE
Fix font size and fix mouse size plus stroke (line)

### ISSUE THREAD

**Issue by mac4kent** [nutti/Screencast-Keys#49]
**Description about the feature**  
*The description about the feature. It is good to clear who will benefit with this feature.*
I can't read too thin and too small font

**Are you willing to contribute about this feature. (Yes/No)**  
no

**Screenshots** [Optional]  
See below and left side you can see too small font and can't read too thin stroke (line)
Need to make very thickness stroke and should be 300pt font not limit 24pt
Mouse should be 300 not 144

![image](https://user-images.githubusercontent.com/4253305/110227229-faab4300-7eaa-11eb-939b-da49d4df0c6f.png)

**Additional comments** [Optional]
For Mac only
![image](https://user-images.githubusercontent.com/4253305/110227258-4d84fa80-7eab-11eb-986f-3b7edffca37c.png)

More space of Display within 5K Retina Display.
![image](https://user-images.githubusercontent.com/4253305/110227265-68f00580-7eab-11eb-8c75-16ec1d1961bf.png)

**Comment by mac4kent** [comment]
I just change code from 24 to 300 font size and mouse too. I am try find out stroke to be thickness in the code.
![image](https://user-images.githubusercontent.com/4253305/110227397-00098d00-7ead-11eb-805b-a9bb4176bcf7.png)

**Comment by mac4kent** [comment]
Need add feature for Mac only please
Shift, Control, Option, and Command too
Not for Windows.

**Comment by nutti** [comment]
@mac4kent 

> Need add feature for Mac only please
> Not for Windows.

Why only macOS?
I don't want to change the add-on's behavior among the platform.

**Comment by nutti** [comment]
@mac4kent 

BTW, I do not reject your request.
I want to know why you want to add this feature only macOS.
I think this improvement will also be effective for Windows.
What do you think?

**Comment by mac4kent** [comment]
I mean keyboard I show you 3 different picture that match for Mac.
![Blender keyboard screencast keys](https://user-images.githubusercontent.com/4253305/110231016-ed518100-7ec9-11eb-8885-4557ff490211.png)
![IMG_0307](https://user-images.githubusercontent.com/4253305/110231022-f3476200-7ec9-11eb-9d25-0c1edbd14afa.png)
![IMG_0308](https://user-images.githubusercontent.com/4253305/110231026-f7737f80-7ec9-11eb-8c8d-e071832f063a.png)

**Comment by nutti** [comment]
@mac4kent 

> Shift, Control, Option, and Command too

I think above request should be on the other issue.
This feature request is not same to this issue.

And also, I want to ask you why the removal of these limitation is needed only for macOS you described in the first comment.
Removing the limitation of font size and mouse size is useful for Windows.

**Comment by mac4kent** [comment]
That is VERY ENOUGH to ask me "WHY WHY WHY" too much.
Gaia Clary know already and think about deaf/blind people must remove limitation. change to unlimit and mouse too thinner need to fix thickness.

**Comment by nutti** [comment]
@mac4kent 

Understood. I was wondering there is a intention for limiting the platform.
Thanks for the clarification.

**Comment by nutti** [comment]
The early patch works for me in Windows system, and does not in macOS system.
I found we need to avoid using `glLineWidth` in macOS system.
Ref: https://developer.blender.org/T57570

We need a time to add this feature to check whether we can realize this feature or not because of the API limitation.

**Comment by nutti** [comment]
Almost done.
Changing stroke width will only support for Blender 2.92 or later in macOS environment which supports `3D_POLYLINE_UNIFORM_COLOR` shader.
We think it is enough because Blender itself can handle this issue after Blender 2.92 was released. (c.f. above the discussion on T57570)

**Comment by mac4kent** [comment]
Oh really thanks. I am use Blender 2.93 Alpha.

**Comment by mac4kent** [comment]
Good job you found out everything. You saw I report ticket to Blender many list and they fix lot and lot bug.

**Comment by nutti** [comment]
@mac4kent 

Is it possible to try the temporary version in your environment?
https://github.com/nutti/Screencast-Keys/archive/issue_49.zip

This version works fine in my macOS environment.

**Comment by mac4kent** [comment]
Thank you for send me link on .zip and I don't know how to do.
![image](https://user-images.githubusercontent.com/4253305/110273267-0ff2a100-7f81-11eb-89ba-99ef8a7466b8.png)

**Comment by nutti** [comment]
@mac4kent 

Thanks for your cooperation.
The installation process is same as `unstable` version.
Could you follow the below **Manual Install** process?

https://github.com/nutti/Screencast-Keys/blob/master/docs/installation.md#manual-install

**Comment by mac4kent** [comment]
This link I don't understand but I found on. my Mac.
![image](https://user-images.githubusercontent.com/4253305/110277637-847e0d80-7f8a-11eb-9d8c-b4a2b8ae2754.png)
![image](https://user-images.githubusercontent.com/4253305/110277709-b4c5ac00-7f8a-11eb-8fa7-6d7e25226c84.png)

Look awesome thank you for feature and look much better.

**Comment by mac4kent** [comment]
I did take screen shot is a Shift + Control + Command.

**Comment by nutti** [comment]
Thanks @mac4kent .

I will merge the patch to the master branch soon.

**Comment by mac4kent** [comment]
Sure no problem

**Comment by nutti** [comment]
The patch is now merged to master branch.

**Comment by mac4kent** [comment]
Cooooooooooool good job.
