### ISSUE TITLE
Change Language

### ISSUE THREAD

**Issue by D36u92** [nutti/Screencast-Keys#5]
Hey is there any way to change the Language for Mittle Mouse etc?

**Comment by nutti** [comment]
This add-on only supports English.
But it is a good extension to change the string on UI.
I will consider to realize this.

**Comment by nutti** [comment]
This feature is now implemented.

@D36u92 

Sorry for late response about this request.
I added this feature just now.

This feature can set an alias about text to be displayed from preference.
![github_20200429](https://user-images.githubusercontent.com/1463952/80597686-2677c400-8a63-11ea-8543-b1d4f2137e0a.png)
I hope this feature meets your requirement.
