### ISSUE TITLE
Display macOS key

### ISSUE THREAD

**Issue by mac4kent** [nutti/Screencast-Keys#50]
Display macOS keys (not Shift, Ctrl, Alt) in macOS environment.

See other link we talk
https://github.com/nutti/Screencast-Keys/issues/49#issuecomment-792221956

**Comment by nutti** [comment]
@mac4kent 

I will fix this issue.
Before our development is finished, you can try to use **Display Event Text Aliases** instead if you want.
You can change the display texts as you want by using this preference.

**Comment by mac4kent** [comment]
Allright thanks I did meet Gaia in SecondLife many years ago.

**Comment by nutti** [comment]
@mac4kent 

I'm considering to change the current text to macOS specific text as follows.

|Current|Change for macOS|
|---|---|
|Alt|Option|
|Ctrl|Command|

I think **Shift** and **OSKey** seems fine as they are.
Feel free to have a comment.

**Comment by mac4kent** [comment]
Oh allright there Mac is different between Control and Command.
When take Screen Shot write into disk is a Shift + Command + F3
When take Screen Shot into chip is a Shift + Control + Command + F3
Blender have special 4 different is Shift, Comtrol, Option, and Command.
Control and Command is different on Blender.

**Comment by nutti** [comment]
Hmm, maybe I should check in my macOS environment how difference exists between macOS and Windows.

**Comment by mac4kent** [comment]
Sure of course and you can look up Blender.app on Edit > Preferences and Keymap then 3D view > 3D View (Global) then click Screencast Keys
![image](https://user-images.githubusercontent.com/4253305/110285073-94501e80-7f97-11eb-8248-dfc28912652c.png)
You can see picture Shift, CTRL, ALT, and CMD
for Mac.

**Comment by nutti** [comment]
I checked the key mapping in my macOS environment.
I try to fix as follows.

|Current|Windows|macOS|
|---|---|---|
|Shift|Shift|Shift|
|Ctrl|Ctrl|Control|
|Alt|Alt|Option|
|OS Key|Windows Key|Command|

Maybe, **OS Key** is a little confusing in both Windows and macOS system.

**Comment by mac4kent** [comment]
Oh really good job. There is correct.
Take your time.

**Comment by nutti** [comment]
@mac4kent 

I almost done to implement this.
If you have a time, it is help for me to check updated add-on.
https://github.com/nutti/Screencast-Keys/archive/issue_50.zip

You can install this version by following the same process you described in other issue.

**Comment by mac4kent** [comment]
Sureeeeeeeeeee.
From my iPad Pro camera record and upload youtube. (Some time hard for my hand hold with iPad Pro 12.9")
https://youtu.be/ksEckvaXn90

ScreenRecord on my iMac and upload youtube.
https://youtu.be/R_Vo-_5KdMw

**Comment by nutti** [comment]
* For OS specific key display

I think you need to disable and enable the add-on.
The preference was remained if you update the add-on without restarting.

* Bad UI display

I found that the shader works only in View3D.
So, it is difficult for us to fix this from the add-on level.
Maybe we should redirect this issue to the Blender's developer to work this shader the other editors.

**Comment by mac4kent** [comment]
Yes I did remove button from Add-on then quit Blender 2.93 Alpha then open Blender 2.93 Alpha then Add-on then import on #50 is new.
Its ok not worry about that. View 3D is fine.

**Comment by nutti** [comment]
Oh, sorry. I found the easy mistake.

Could you try again? I think this will work fine.
https://github.com/nutti/Screencast-Keys/archive/issue_50.zip

**Comment by mac4kent** [comment]
Look so AWESOME and I just take camera record on my iPad Pro.
Upload Youtube.
https://youtu.be/MW9fT1msrsc
You are so beautiful job.

**Comment by nutti** [comment]
This patch is now merged to the master branch.
Thanks for the validation of this patch @mac4kent
