### ISSUE TITLE
Display view push the N key see Screencast Keys

### ISSUE THREAD

**Issue by mac4kent** [nutti/Screencast-Keys#51]
MacOS 11 Beta
Blender 2.93 Alpha
Screencast Key 2.5

You may remove "Bug" change other word I don't know which right word.

If you want to change it up to you. I made Affinity Designer to show you.
![Screencast Key 3 5](https://user-images.githubusercontent.com/4253305/110403111-67504a00-8031-11eb-8a34-87b2649eaa40.png)

**Comment by nutti** [comment]
@mac4kent 

Thanks for your proposal. I tried to improve the UI.
https://github.com/nutti/Screencast-Keys/archive/develop.zip

What do you think about this new UI?
<img width="284" alt="github_20210309" src="https://user-images.githubusercontent.com/1463952/110444887-e2346600-8100-11eb-8a61-b8d91a4e13a8.png">

**Comment by mac4kent** [comment]
Look so great. I like it.

**Comment by nutti** [comment]
Merged. Thanks for the proposal.

**Comment by mac4kent** [comment]
Sure you are welcome
