### ISSUE TITLE
Display Screencast Keys over mouse background.

### ISSUE THREAD

**Issue by mac4kent** [nutti/Screencast-Keys#52]
Both Windows and Macintosh.
MacOS 11.3 Beta (20E5196f)
Blender 2.93 Alpha but not matter previous version is the same.

See youtube now you get know more about Screencast Keys background
Take your time and work team with Gaia and Blender developers.
https://youtu.be/HAGcd4YicpQ
I am kind too deeply inspect for bug many years about Mac, Blender, iPad, other app and etc.
I already stop inspect on Avastar any more Gaia know already.

**Comment by mac4kent** [comment]
Allright

**Comment by mac4kent** [comment]
My brain appear and I notice that Text Editor You may try. See picture
![image](https://user-images.githubusercontent.com/4253305/110563016-74d40580-80ff-11eb-91e8-82d4b690bcbd.png)

See youtube less than 1.49 not 1.50 and you are right.

I remember I can tell yesterday that happen. I show you picture that example:
![image](https://user-images.githubusercontent.com/4253305/110564288-6d156080-8101-11eb-8853-85f9b30d415d.png)


https://youtu.be/1LV0OIyrEDo
and
https://youtu.be/gnsBKuOBmJ0

**Comment by nutti** [comment]
Maybe you're right.
This issue is now reproduced in my environment with a simple add-on.
So, this issue comes from the Blender itself.

**Comment by mac4kent** [comment]
I agree.

**Comment by mac4kent** [comment]
I forget to show you on youtube. Drag left and right on line thick to show you.
I want to know where did you made code like SVG some where like stroke like mouse.

**Comment by nutti** [comment]
This is a code to draw mouse icon.
https://github.com/nutti/Screencast-Keys/blob/9e2b644b8e5b4b650c5776cd482ef25b8cdad769/src/screencast_keys/ops.py#L56-L143

About this issue:
I will post the issue to D.B.O after cleaning up my test code. Thanks for your investigation.

**Comment by mac4kent** [comment]
Sure thanks.

**Comment by mac4kent** [comment]
I just search hard and I see. change 5 on line 189
You may find other way on thickness some where.
![image](https://user-images.githubusercontent.com/4253305/110590081-29841c00-812c-11eb-90f7-bc58e6e6b137.png)

See youtube
https://youtu.be/8IERJMuUSp8

**Comment by mac4kent** [comment]
Above youtube did not quit and open Blender.app yet.

Below youtube I did quit and open Blender.app to show you.
https://youtu.be/iQNOqX6pRyk

**Comment by nutti** [comment]
If you want to specify the line thickness explicitly.
You need to consider to change codes.

From

https://github.com/nutti/Screencast-Keys/blob/9e2b644b8e5b4b650c5776cd482ef25b8cdad769/src/screencast_keys/ops.py#L198-L201

To

```python
bgl.glVertex3f(x, y, 0)
```

**Comment by mac4kent** [comment]
sure

**Comment by mac4kent** [comment]
Sculpting tab on top

![image](https://user-images.githubusercontent.com/4253305/110607549-2a26ad80-8140-11eb-8d54-994fe8298cb8.png)
![image](https://user-images.githubusercontent.com/4253305/110607696-4de9f380-8140-11eb-92cb-c8e71af03471.png)

https://youtu.be/wH6GrLk-dJU

**Comment by nutti** [comment]
I created the issue on D.B.O.
If you have an additional information, you may add it.
https://developer.blender.org/T86485

This discussion should be continued on the D.B.O.
So I will close this issue for now.

**Comment by mac4kent** [comment]
sure no problem

**Comment by mac4kent** [comment]
Did you get message from Blender Developer issue? 
https://developer.blender.org/T86485

**Comment by mac4kent** [comment]
Hello
