### ISSUE TITLE
How run screencast-keys without blender

### ISSUE THREAD

**Issue by artb1sh** [nutti/Screencast-Keys#53]
**run screencast-keys without blender**  
*run screencast*

**No**

**Comment by nutti** [comment]
Screencast Key add-ons does not work without Blender.
This project is one of the **Blender** add-on, not targeting for general application.

**Comment by ldo** [comment]
If you want a more general one, try [key-mon](https://github.com/ldo/key-mon).

**Comment by artb1sh** [comment]
@ldo thanx you!
