### ISSUE TITLE
Retain settings after disabling/re-enabling the addon

### ISSUE THREAD

**Issue by hced** [nutti/Screencast-Keys#55]
I'm only using this addon occasionally, so I'd like to have it disabled when not needing it, to save space in the N-panel. When re-enabling it, my customizations are gone. It would be awesome if it could remember them, but maybe this is just how Blender works?

**Comment by nutti** [comment]
@hced 

I reproduced this error.
BTW, is there any other add-ons which preserves the preference when you re-enable the add-on on the Preference?

**Comment by hced** [comment]
Actually, not sure if any add-on would retain their settings after disabling them. :-) Very likely that is the case. Not on my computer atm so I can’t check.

**Comment by nutti** [comment]
@hced 

Thanks.
I think remaining add-on preferences after disabling the add-on is not the best way in Blender because the official add-on does not remain the preference after disable the add-on.

>  I'd like to have it disabled when not needing it, to save space in the N-panel.

But, I think this will be solved by #56 .
So, I will close this issue for now.
