### ISSUE TITLE
Checkbutton in Overlay menu (and remove N-panel)?

### ISSUE THREAD

**Issue by hced** [nutti/Screencast-Keys#56]
Just a humble request for the UI:

A checkbutton in the Overlay menu for turning the addon on/off. And also disabling the N-panel menu by default or removing that part of the code completely. (Personally, I think addon settings should be kept to the Preferences > Add-on settings as much as possible, especially if they're not going to be changed very often.)

Here's an example of another addon ([Mesh Check](https://github.com/pistiwique/mesh_check_BGL_edition)), where this is made. And I definitely regard Screencast Keys to be an overlay-related thing, so I think it's more logical this way.

(Finally, I'm very thankful for all your great work making this add-on and I only mean this as a constructive idea, not to be unthankful. And I understand totally if you don't find the time to make this change!)

![screencast_keys_overlay_settings](https://user-images.githubusercontent.com/93350/119699414-71c0f980-be52-11eb-8321-bf1a3ee94ee0.png)

**Comment by nutti** [comment]
@hced 

I think this is a duplicate of #35.
This feature is already supported, and you can see how to enable this from the Preferences.

![github_20210527](https://user-images.githubusercontent.com/1463952/119815175-3a238180-bf26-11eb-9457-dd206b98d4d5.png)

I also find the bug on it, but it is fixed now.
Could you try the latest (unstable) version?
https://github.com/nutti/Screencast-Keys/blob/master/docs/installation.md#manual-install

**Comment by nutti** [comment]
@hced 

Is there any update about this issue?

**Comment by hced** [comment]
Sorry for late reply and it's middle of the night now so I might be missing something, but. Downloaded latest unstable (Blender 2.92) and the Sidebar-disable worked, but I don't see anything in the Overlay menu:

Overlay option OFF:

![overlay_option_off](https://user-images.githubusercontent.com/93350/120944667-07536780-c736-11eb-8f97-1d849dfbb4b0.png)

Overlay option ON:

![overlay_option_on](https://user-images.githubusercontent.com/93350/120944681-176b4700-c736-11eb-82a7-fafe91ef8673.png)

So I tried completely removing the addon via disable + remove in Prefs. Then restarted Blender, installed the `Screencast-Keys-master.zip` and got this confirmation in lower status bar:

![install_confirmation](https://user-images.githubusercontent.com/93350/120944812-ba23c580-c736-11eb-90a7-4b8ee9b1ca66.png)

However … the addon now won't show up in my add-on list. (Not because of the classic when you've got something else written in the search field, which often gets me. I even searched `screencast` and it doesn't show up, which is strange as I got the above confirmation of successful installation.) Which makes me wonder what version I really had installed when I did the first update, by just choosing install over the existing version prior to this attempt.

**Comment by nutti** [comment]
@hced 

Unstable version does not support the installation method from zip file.
Could you check again the below process?
https://github.com/nutti/Screencast-Keys/blob/master/docs/installation.md#manual-install

In my environment (Windows 10, Blender 2.92), the add-on works correctly (Overlay option also works fine).

**Comment by hced** [comment]
@nutti 

Great! Confirming the overlay menu function works like a treat now! Closing this issue!

**Comment by nutti** [comment]
I'm glad to help solving your issue.
