### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by JoelGodin** [nutti/Screencast-Keys#64]
**System Information**
Apple M1 8core
  
* OS: MacOS Big Sur
* Blender version: 2.93.1
* Add-on version: comes-with, github version, and latest unstable version

**Expected behavior**  
Cannot install, gives error below.

**Screenshots/Files**

<img width="1447" alt="1" src="https://user-images.githubusercontent.com/9205295/126071976-51887586-26f0-45e7-846c-8fabf0949404.png">

**Comment by JoelGodin** [comment]
Just tried version 3.5 now and got different error.
<img width="1112" alt="2" src="https://user-images.githubusercontent.com/9205295/126072249-2426ddde-2f8f-4be8-b39e-2b17d0057dde.png">

**Comment by nutti** [comment]
@JoelGodin 

I think this relates to #61 .

Could you try to restart/reinstall Blender or the add-on?
Maybe this is caused from the environment.

**Comment by JoelGodin** [comment]
Yes, reinstalled Blender, than worked.
