### ISSUE TITLE
Type error in Blender 2.93

### ISSUE THREAD

**Issue by crawfis** [nutti/Screencast-Keys#66]
**System Information**
  
* OS: Windows 10 Pro
* Blender version: 2.93.1
* Add-on version: 3.0

**Expected behavior**  
Properties are displayed for screencast

**Description about the bug**  
Python error (Type expected an integer) appears when enabling the Addon.

**Screenshots/Files** [Optional]  
![image](https://user-images.githubusercontent.com/1799584/126996298-9bda2db1-dae5-46bf-9b72-135350587f7d.png)

**Additional comments** [Optional]
I just installed Blender and then was installing this addon (after Bool and Auto Mirror). New to Blender, but tutorials seem to suggest this is the way to do it.
Uninstalled and reinstalled. Disabled and Enabled several times, etc. to try to get it to work. Also reloaded all scripts.

**Comment by nutti** [comment]
Same as #45 

Please use this add-on whose version is > 3.5
