### ISSUE TITLE
addon doesnt work in blender 2.93.3

### ISSUE THREAD

**Issue by WizardSemyon** [nutti/Screencast-Keys#68]
**System Information**
  
* OS: [e.g. Windows]
* Blender version: [e.g. 2.93.3]
* Add-on version: [e.g. 3.0]

**Expected behavior**  
*on this addon and see the keys*

**Description about the bug**  
*have error report when I on this in side bar. But addon is on. And dont showing keys in viewport*.*

**Screenshots/Files** [Optional]  
*It is good to solve the bug if you attach the screenshots or .blend file.*
https://yadi.sk/i/-LcI6i5JWzFqdQ  screenshot
blendfile https://yadi.sk/d/jR1_4gQ971EXKA

**Additional comments** [Optional]
I very need this addon.

**Comment by nutti** [comment]
Same as #45

Please use version 3.5 instead of 3.0.
