### ISSUE TITLE
Report Error when press CapsLock

### ISSUE THREAD

**Issue by Leroy-X** [nutti/Screencast-Keys#7]
**System Information**
  
* OS: windows
* Blender version: 2.80 5dd8c3f0cb83 20190627
* Add-on version: 3.0

when I press Caps Lock, it's report error, and stop work, I must re-check in N panel.
Hope can fix this, thanks.

by the way, does it will display the icon mode in the future, sorry my english,thanks.

**Description about the bug**  
*The description about the bug.*

**Screenshots/Files** [Optional]  
*It is good to solve the bug if you attach the screenshots or .blend file.*

**Additional comments** [Optional]

**Comment by MALMLup** [comment]
**System Information:**
 · OS: Windows 10
 · Blender version: 2.80 b63f0266a056-win64 (RC2, J2019-Jul-24)
 · Add-on version: 3.0
**Repor Error when press CapsLock, and stop work:**
![image](https://user-images.githubusercontent.com/32163414/61776512-78682b00-adfb-11e9-9200-a0f386fb52a7.png)

**Comment by nutti** [comment]
This is now fixed by #10
