### ISSUE TITLE
Push last key doesn't appear text September 20, 2021

### ISSUE THREAD

**Issue by mac4kent** [nutti/Screencast-Keys#70]
![image](https://user-images.githubusercontent.com/4253305/134103057-b3c7506f-0e6f-41df-9a67-15902e8a8185.png)
Blender 3.0 Alpha
Screencast Key version 3.6.0

Push the "g" key yes appear text on display then push the "x" key cause not appear text on display.
Same S yes appear text then X doesn't appear text.
r then x not appear
everything first push key appear then next second doesn't appear
also push the "s" key yes appear text display then push the "ENTER" key doesn't appear text on display.

See YouTube: https://youtu.be/8Jrekn79vQ0

**Comment by nutti** [comment]
This is because **Get Event Aggressively** option is disabled in 3.0.
**Get Event Aggressively** option has not supported 3.0 yet because the internal of Blender may be changed in near future.
Please wait until Blender 3.0 beta is released.

**Comment by mac4kent** [comment]
No that is not true.
Blender 2.9.4 and Blender 3.0 is the same problem exactly on youtube is the same as 2.9.4

**Comment by nutti** [comment]
I checked that Blender 2.93.5 works fine to me.

I think Blender 2.94 has also not released yet, so we could not support 2.94 as well.

**Comment by mac4kent** [comment]
Ok

**Comment by mac4kent** [comment]
I mean Blender 2.93.4 
![image](https://user-images.githubusercontent.com/4253305/134115270-35cb99f3-efa2-47f3-9ef7-2d441c4180f8.png)

**Comment by nutti** [comment]
OK, but I think 2.93.4 will work on your macOS environment.
I checked this on my macOS environment.

Please try 2.93.5 instead or recheck the add-on's installation process again.

**Comment by mac4kent** [comment]
Really? 2.93.5 I don't know where.

**Comment by mac4kent** [comment]
Open Preferences > Add ons then uncheck Screencast Key then check Screencast Key cause appear error 
![image](https://user-images.githubusercontent.com/4253305/134117140-e0697f1b-2131-4bc6-9903-91d28b063f77.png)

**Comment by nutti** [comment]
2.93.5 can be downloadable from [experimental page](https://builder.blender.org/download/daily/).

And your error seems very common in Blender add-on installation process.
Please re-install Blender or add-on again.

**Comment by nutti** [comment]
Did you try the preference **Enable on Startup*?
@CheeryLee fixes this issue with a great effort. (c.f. #62)

https://github.com/nutti/Screencast-Keys/blob/master/docs/faq.md#screencast-keys-is-disabled-after-opening-a-new-blend-file-or-restarting-blender
https://github.com/nutti/Screencast-Keys/blob/master/docs/tutorial.md#enable-on-startup

**Comment by mac4kent** [comment]
Open preferences on Screencast Key I did not put check box turn on Startup yet. 
Let me turn enable on Startup

**Comment by mac4kent** [comment]
Open Blender 2.93.4
Preferences
Screencast Key then check box turn on Enable on Startup then quit Blender
Open Blender 2.93.4
appear there Screencast Key it work but same g appear, x not appear, y not appear then ESC not appear.
