### ISSUE TITLE
3.1 - SK_Preferences Registration Error

### ISSUE THREAD

**Issue by Erindale** [nutti/Screencast-Keys#73]
**System Information**
  
* OS: Windows 11
* Blender version: 3.1 Alpha Master
* Add-on version: 3.6

**Expected behavior**  
*The behavior you expect about the feature you reported.*
Enabling the addon fails.

**Description about the bug**  
*The description about the bug.*
When enabling the add-on, it errors once with the "font_size" error and then all subsequent errors are the "already registered" error.

**Screenshots/Files** [Optional]  
*It is good to solve the bug if you attach the screenshots or .blend file.*
![image](https://user-images.githubusercontent.com/67860352/142649094-3b2703d2-bc77-43e7-abb9-2640180e1eb8.png)

**Comment by nutti** [comment]
@Erindale 

Have you checked the [FAQ](https://github.com/nutti/Screencast-Keys/blob/master/docs/faq.md#failed-to-install-this-add-on)?

There is a similar case found in `Failed to install this add-on`.

**Comment by Erindale** [comment]
@nutti 
I have checked. It's an odd one because I've been using the add-on for months but it's just stopped working in the last few days.
I can use it in a build of 3.1 Alpha from the 4th of November but my builds from the 10th and 18th both fail to enable the add-on.

**Comment by mac4kent** [comment]
Me too same exactly. I put youtube plus send report a bug to Blender Developers.
Also I can show you they did put syntax fixed on Mac with Graph Editor stroke thickness for Mac on Blender 3.1.0

Resolve on Graph Editor stroke thickness.
https://developer.blender.org/T93206

Report a bug.
https://developer.blender.org/T93254

**Comment by nutti** [comment]
@Erindale 

Thanks for your feedback.
I could reproduce this error on my environment.

@mac4kent 

I have already consulted with Blender developers about including this add-on to Blender itself.
https://developer.blender.org/T76611

From the discussion with Blender developers, I noticed that Screencast Keys in Blender 2.6 had a potential issue to solve some technical issues.
Our add-on solved some issues but it hacked some Blender code, so it is difficult to merge.

About this issue, I could fortunately reproduce this error on my environment.
So, I will tackle to solve this issue.

**Comment by mac4kent** [comment]
@nutti Yes of course and I give you link and you can reach right syntax for stroke thickness that what Graph Editor resolve stroke thickness.

**Comment by mac4kent** [comment]
https://youtu.be/0yOVSa7U5qE

**Comment by nutti** [comment]
@mac4kent 

Sorry, I could not understand what is relationship between @Erindale 's issue and yours.
Graph Editor is not our region, so I'm going to fix below @Erindale 's issue.

> When enabling the add-on, it errors once with the "font_size" error and then all subsequent errors are the "already registered" error.

**Comment by nutti** [comment]
@Erindale @mac4kent 

I fixed the issue, and fixed patch is now in master branch (unstable version).
You can try unstable version by using manual installation.
https://github.com/nutti/Screencast-Keys/blob/master/docs/installation.md#manual-install

I will close this issue.
If you have any other issues, please reopen or create new issue.

Thanks for your early attempt about this add-on.
