### ISSUE TITLE
Stroke width of mouse line for Mac

### ISSUE THREAD

**Issue by mac4kent** [nutti/Screencast-Keys#74]
**Description about the feature**  
*The description about the feature. It is good to clear who will benefit with this feature.*
Graph Editor Blender 3.1.0 on MacOS 12.0.1
![image](https://user-images.githubusercontent.com/4253305/142770128-9bc92fe2-7749-4209-9f75-fd9425e461f7.png)

**Are you willing to contribute about this feature. (Yes/No)**  
Yes

**Screenshots** [Optional]  
![image](https://user-images.githubusercontent.com/4253305/142769899-b3565728-0ed5-44aa-abd6-47c39f5e8006.png)

*It is good to understand the features if you attach the screenshotsfile.*

**Additional comments** [Optional]
I don't know how to tell syntax but I give you example about code width stroke.
![image](https://user-images.githubusercontent.com/4253305/142770041-8b9f513f-541e-4ced-8c88-b843559ed04c.png)

Also I see Preferences > Screencast Key still 3.6.0 version yet.
I want to help you but I don't know how to work on syntax.

**Comment by nutti** [comment]
@mac4kent 

Does the option **Line Thickness** work on your environment?
https://github.com/nutti/Screencast-Keys/blob/master/docs/tutorial.md#line-thickness

**Comment by mac4kent** [comment]
Version: unstable
Yes it work as well line stroke Thickness of course but still is the same. https://youtu.be/iHvhsOa48wA That is all I let you know.

**Comment by nutti** [comment]
This issue comes from #52 (Sorry for forget) and https://developer.blender.org/T86485.
After applying [this workaround](https://developer.blender.org/T86485#1153201), this issue has been solved.
The patch has already been merged in the unstable version.
