### ISSUE TITLE
Possible future cast issue

### ISSUE THREAD

**Issue by londo19** [nutti/Screencast-Keys#77]
Hi there,

For a project I needed to run a screencast addon in a Blender > 3.x.
Well, I wasn't able to activate your addon because it throws this error:
`ValueError: bpy_struct "SK_Preferences" registration error: 'font_size' IntProperty could not register (see previous error)`

the function `get_user_preferences` in preferences,py at line 159 and 181 is causing it, because it returns `float` instead of `int`.
Strange thing is that this function returns `int` in Blender 2.93.

Looks like the return value of some function has been changed you depend on. 

Anyway just wanna let you know.

good work 👍

**Comment by nutti** [comment]
@londo19 

Thanks.
Fortunately, this issue has already fixed in #73 .
