### ISSUE TITLE
Blender 3.0 is release today December 3, 2021

### ISSUE THREAD

**Issue by mac4kent** [nutti/Screencast-Keys#78]
**System Information**
  
* OS: [e.g. Windows]
* 
![image](https://user-images.githubusercontent.com/4253305/144689046-f83bc6a4-cd0d-4723-b810-797c47c12035.png)

* Blender version: [e.g. 2.79]
Blender 3.0 is Release December 3, 2021

* Add-on version: [e.g. 5.2]
3.6.0

**Expected behavior**  
*The behavior you expect about the feature you reported.*
Experimental
     [√] Get Aggressively 
is not active. Need to fix

**Description about the bug**  
*The description about the bug.*
Experimental
     [√] Get Aggressively 
![image](https://user-images.githubusercontent.com/4253305/144689190-368e8f11-d77b-4e20-9810-d47f8d38325b.png)
is not active. Need to fix

**Screenshots/Files** [Optional]  
*It is good to solve the bug if you attach the screenshots or .blend file.*
N/A

**Additional comments** [Optional]

![image](https://user-images.githubusercontent.com/4253305/144689010-485412bd-4455-4879-afee-8159316335a4.png)

**Comment by mac4kent** [comment]
![image](https://user-images.githubusercontent.com/4253305/144699037-8484d8f6-9cb7-4e33-8aa2-15cd64a6055b.png)

Blender 2.93.7 is beta
Get Event Aggressively it work

Blender 3.0.0 is full version
Get Event Aggressively not work

**Comment by nutti** [comment]
Supported **Get Event Aggressively** option for Blender 3.0.
