### ISSUE TITLE
cant turn on in 3.1

### ISSUE THREAD

**Issue by 3d-illusions** [nutti/Screencast-Keys#79]
**System Information**
  
windows 10, blender 3.1 alpha

Error when enabling from the n panel:

![image](https://user-images.githubusercontent.com/22356973/144750661-0b4007e3-2225-4067-bc29-37c7626a1e6a.png)

**Comment by 3d-illusions** [comment]
also this bug when trying to enable in the preferences:

![image](https://user-images.githubusercontent.com/22356973/144750821-ecfd90e0-0c1c-44fe-a15e-aa6b27ca6fb4.png)

**Comment by BluePrintRandom** [comment]
https://developer.blender.org/D8960 I think this is the issue

int font_size needs to be a float instead of a int now

**Comment by 3d-illusions** [comment]
yep, font_size, mouse_size, and something else needed changing to float instead of int, working fine now 👍  I'd upload the diff, but I didn't have git in the folder.  It's just 3 lines in the preferences.py anyway.

**Comment by nutti** [comment]
This issue has already fixed in #73.
