### ISSUE TITLE
cannot install screencast keys for blender 3.1 mac a1 chip

### ISSUE THREAD

**Issue by luckychris** [nutti/Screencast-Keys#80]
![image](https://user-images.githubusercontent.com/232549/144760970-33ec57a7-b42a-4623-b2d9-914917480697.png)

![image](https://user-images.githubusercontent.com/232549/144760979-57093ce6-9adb-463a-8fc8-77089f8ef68a.png)

**Comment by nutti** [comment]
See [FAQ](https://github.com/nutti/Screencast-Keys/blob/master/docs/faq.md#failed-to-install-this-add-on).

It seems that this is common error in this add-on, and can be fixed by applying above workaround.
