### ISSUE TITLE
Checkbox error

### ISSUE THREAD

**Issue by guitarpeggio** [nutti/Screencast-Keys#81]
After clicking the checkbox to activate Screencast key I get an error message from Blender and I have no idea how to fix that.
![Error](https://user-images.githubusercontent.com/94455238/145036989-7bf0a265-b55e-44bc-93ff-04c3e69fc2f9.PNG)
.

**Comment by nutti** [comment]
See [FAQ](https://github.com/nutti/Screencast-Keys/blob/master/docs/faq.md#failed-to-install-this-add-on).

It seems that this is common error in this add-on, and can be fixed by applying above workaround.

**Comment by guitarpeggio** [comment]
Thanks for replying. Version 3.5 works properly.
