### ISSUE TITLE
Unable to activate the Addon in Blender 3.1

### ISSUE THREAD

**Issue by maxim1967** [nutti/Screencast-Keys#82]
**System Information**
  

Blender version: [e.g. 3.1 Alpha]
Add-on version: [e.g. 3.5 & 3.6]

The Addon cannot be activated.
![Снимок](https://user-images.githubusercontent.com/62519357/145086212-268f8248-2fd3-4cca-a761-149139e55a1f.JPG)

**Comment by nutti** [comment]
Same as #73 .

Please use unstable version for now.
