### ISSUE TITLE
Suggestion to use a vector mouse indicator

### ISSUE THREAD

**Issue by Almaz** [nutti/Screencast-Keys#88]
Hi guys,

I suggest that you use a vector mouse indicator in your addon, which will look more aesthetically pleasing.

I drew such an image in a vector: [https://nimb.ws/OaptbR](https://nimb.ws/OaptbR) and am ready to provide the SVG file.

Thank you!

**Comment by nutti** [comment]
@Almaz 

I agree with this idea, but Python API does not support reading SVG file as a programmable way.
How about using the PNG/JPEG file to specify the image for rendering mouse?

**Comment by Almaz** [comment]
I prepared [a set of bitmap graphics](https://drive.google.com/file/d/1wbsqUjwvqLnNLV_6xEc1FWWMGidWdBOR/view?usp=sharing). 
Please take a look and write me if you need corrections.

**Comment by nutti** [comment]
Maybe this feature should be extensible.
So, I'm considering to add an option to specify the image path instead of loading the specific image.

**Comment by nutti** [comment]
This feature is now merged to master branch.

![issue_88_1](https://user-images.githubusercontent.com/1463952/157845632-73e75159-0158-442a-a76a-5f6a82d61b22.png)

![issue_88_2](https://user-images.githubusercontent.com/1463952/157845611-5f5adeaa-03f2-484a-be24-0bba034bb2db.png)

Thanks for your feature request.

**Comment by Almaz** [comment]
Great job! Thank you!
