### ISSUE TITLE
Not displaying overlay on Blender 2.80, Mac 10.14.5

### ISSUE THREAD

**Issue by rw3iss** [nutti/Screencast-Keys#9]
**System Information**
  
* OS: Mac 10.14.5
* Blender version: 2.80
* Add-on version: 3.0.0

**Expected behavior**  
Should show overlay with keyboard pressed keys while working.

**Description about the bug**  
It installs fine, shows up in tools panel, but no overlay with the keys ever shows anywhere. I tried changing/selecting different regions, am never able to see the overlay/keys.

**Screenshots/Files** [Optional]  
https://i.imgur.com/eS47NSs.mp4

**Comment by FridayIsTheBest** [comment]
You need to check check-mark left from "Screencast Keys", it is disabled by default.
I was certain that this plugin doesn't work too. If someone installs it, you can assume they want to use it. Or at least write about it with bold letters in project description -> how to use.

**Comment by rw3iss** [comment]
Thanks for the update. Just saw they are supporting 2.8 now, and there's a more convenient 'Start Shortcut VUr' in the "Shortcut VUr" panel in the 3D viewport.
