### ISSUE TITLE
Screencast keys throws error on 3.1

### ISSUE THREAD

**Issue by 3dcinetv** [nutti/Screencast-Keys#90]
**System Information**
  
* OS: Windows 10 64x pro
* Blender version: 3.1.0 alpha
* Add-on version:  3.6.0

**Expected behavior**  
The addon causes an error about parsing text on the screen.

**Description about the bug**  
The addon cannot be activated on Blender 3.1

**Screenshots/Files** [Optional]  
*It is good to solve the bug if you attach the screenshots or .blend file.*
https://imgur.com/NkFeDv3

**Additional comments** 
Should I delete my previous Blender (2.8x-2.9x) screencast addons?

**Comment by nutti** [comment]
Please see [FAQ](https://github.com/nutti/Screencast-Keys/blob/master/docs/faq.md#failed-to-install-this-add-on).

Related error can be found in these referenced issues.
I think re-installation of the add-on is needed.

**Comment by 3dcinetv** [comment]
This is the first time install. 
Btw, you generally wait for user feedback first, before closing an issue.

**Comment by nutti** [comment]
> Should I delete my previous Blender (2.8x-2.9x) screencast addons?

I saw this message, so it seemed a same as the issues already reported.
Also I could not make sense about `This is the first time install.`. 
Which message is correct `delete my previous Blender (2.8x-2.9x) screencast addons` or `first time install`.
Actually, I have not reproduced this error, so I need to get more information when you encounter this issue even if you try to re-install blender or add-on.

Also, it is very helpful to discuss the issue which is reported originally (In this case, discuss at #61 is prefer)
It becomes difficult to track the issues which comes from the same issue.
