### ISSUE TITLE
in Blender 3.1 i got an error if i check the "Screencast cast Keys"

### ISSUE THREAD

**Issue by luckychris** [nutti/Screencast-Keys#94]
**System Information**
  
* OS: MacOS
* Blender version: 3.1
* Add-on version: 

![image](https://user-images.githubusercontent.com/232549/151499696-1a8834f4-f520-47d3-98db-4a2a286b07f4.png)

![image](https://user-images.githubusercontent.com/232549/151499790-13f1fe86-6250-4ab4-aa9c-6a4efefc2a97.png)

**Comment by nutti** [comment]
@luckychris 

See FAQ.
This issue has already fixed in newest version.

**Comment by luckychris** [comment]
thanks for the fast answer....unfortunately the 3.5 version throws another error :( i open a new issue
