### ISSUE TITLE
failed enabling the add-on

### ISSUE THREAD

**Issue by luckychris** [nutti/Screencast-Keys#95]
**System Information**
  
* OS: MacOS
* Blender version: 3.1
* Add-on version: 3.5

When trying to enable the add-on i got:

![image](https://user-images.githubusercontent.com/232549/151512698-2a09d934-aaa1-4794-953b-68357a9ebe54.png)

**Comment by nutti** [comment]
@luckychris 

There was also same issue.
Please also see the [FAQ](https://github.com/nutti/Screencast-Keys/blob/master/docs/faq.md#failed-to-install-this-add-on).
Especially issue #64 may be help to solve your issue.

**Comment by luckychris** [comment]
well at least now i got another error after reinstalling blender...
