### ISSUE TITLE
enabling the add-on brings up this error

### ISSUE THREAD

**Issue by luckychris** [nutti/Screencast-Keys#96]
**System Information**
  
* OS: MacOS
* Blender version: 3.1
* Add-on version: 3.5

![image](https://user-images.githubusercontent.com/232549/151516553-3f9b2ee3-af82-45d6-9724-6399b2a02853.png)

**Comment by luckychris** [comment]
and yes, i reinstalled blender

**Comment by nutti** [comment]
@luckychris 

Same as #73 .
Please update to latest (unstable) version.

**Comment by luckychris** [comment]
thank you for your patience, yep, the latest build and manual installation did it. THANK YOU !!!!!!!!
