### ISSUE TITLE
Error when activating the extension

### ISSUE THREAD

**Issue by HattoriHanzuo** [nutti/Screencast-Keys#98]
**System Information**
  
* OS: WIndows 10 21H2 [Build: 19044.1526]
* Blender version: 3.0.1
* Add-on version: 3.0.0

**Expected behavior**  
*The behavior you expect about the feature you reported.*

**Description about the bug**  
I have downloaded Screecast-keys from the original repository.

Installation worked... 
I can't confirm the functions.

Error message is displayed in the tool window. 
Error occurs as soon as the checkbox for the extension is activated. 

**Screenshots/Files** [Optional]  

![image](https://user-images.githubusercontent.com/17326124/154862494-1c10d1d5-c1b9-445c-bc20-507ee83fde88.png)

**Additional comments** [Optional]

**Comment by nutti** [comment]
Duplication of #45 .
Please see [FAQ](https://github.com/nutti/Screencast-Keys/blob/master/docs/faq.md#error-typeerror-an-integer-is-required-got-type-_propertydefered).

**Comment by HattoriHanzuo** [comment]
I have reinstalled Blender... Unfortunately without success... The message remains the same...

In my opinion, it is a different problem than #45

My error message has to do with ops.py.

**Comment by nutti** [comment]
@HattoriHanzuo 

Sorry, I misunderstood the issue.
I think it relates to the issue #73.
Could you try the unstable version instead?
https://github.com/nutti/Screencast-Keys/blob/master/docs/installation.md#manual-install

**Comment by HattoriHanzuo** [comment]
This worked very well... I am very grateful to you... I wish you another wonderful day. And thank you for the development of the add-on <3

**Comment by HattoriHanzuo** [comment]
Can you still tell me how I get displayed in the display from the addon what function the hotkey has that I just made.... So if I press Shift+A, that in my display is that I have opened the Add menu...
